stPage Class Reference
GBDI Arboretum
Version Release 1
stPage Class Reference
#include <stPage.h>
Public Member Functions
stPage (stSize size, stPageID pageid=0)
virtual ~stPage ()
virtual void Write (stByte *buff, stSize n, stSize offset)
virtual stSize GetPageSize ()
virtual stByte * GetData ()
stPageID GetPageID ()
void SetPageID (stPageID pageID)
void Copy (stPage *page)
void Clear ()
Protected Attributes
stByte * Buffer
stSize BufferSize
Detailed Description
This class abstracs a physical disk page in memory. It will allow some functions related with memory manipulation and page identification.
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Enzo Seraphim (serap.nosp@m.him@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Version
1.0
Definition at line 94 of file stPage.h.
Constructor & Destructor Documentation
stPage::stPage (stSize size, stPageID pageid = 0)
Creates a new page.
Parameters
size The page size in bytes.
pageid Page id.
virtual stPage::~stPage () virtual
Disposes this page and free all allocated resources.
Member Function Documentation
void stPage::Clear ()
This method will clear this page (set all bytes to 0).
Referenced by stMNode::RemoveAll(), stSlimNode::RemoveAll(), and stDFNode::RemoveAll().
void stPage::Copy (stPage * page)
This method will copy the content of a given page to this page. Both pages must have the same size.
Parameters
page Source page.
Warning
This method will not perform error checking unless stDEBUG is defined at compile time.
virtual stByte* stPage::GetData () virtual
Returns the pointer to the data array. This method allows the direct access to the internal page data array. It will be used by the stDiskPageManager to read/write this page from/to the disk.
Avoid to use this method. If a read/write operation is required, use Read() and Write() methods instead.
Returns
The pointer to the data array of this page.
Reimplemented in stLockablePage.
Referenced by stDFNode::stDFNode(), stMNode::stMNode(), and stSlimNode::stSlimNode().
stPageID stPage::GetPageID () inline
Returns the ID of this page.
Returns
The ID of this page.
See also
SetPageID()
Definition at line 148 of file stPage.h.
Referenced by stDummyNode::GetPageID(), stVPNode::GetPageID(), stGHNode::GetPageID(), stMNode::GetPageID(), stSlimNode::GetPageID(), and stDFNode::GetPageID().
virtual stSize stPage::GetPageSize () virtual
Returns the page size in bytes.
Returns
The page size in bytes.
Reimplemented in stLockablePage.
void stPage::SetPageID (stPageID pageID) inline
Sets the ID of this page.
See also
GetPageID().
Definition at line 158 of file stPage.h.
virtual void stPage::Write (stByte * buff, stSize n, stSize offset) virtual
Writes n bytes to this page and sets the cursor to the next writing position.
Parameters
buff The byte array to be written.
offset Position where the buff will be written.
n Number of bytes to write.
Warning
This method will not perform error checking unless stDEBUG is defined at compile time.
Reimplemented in stLockablePage.
Member Data Documentation
stByte* stPage::Buffer protected
The page (buffer).
Definition at line 183 of file stPage.h.
Referenced by stLockablePage::GetTrueData().
stSize stPage::BufferSize protected
The page size.
Definition at line 188 of file stPage.h.
Referenced by stLockablePage::GetTruePageSize(), and stLockablePage::Lock().
The documentation for this class was generated from the following file:
stPage.h
Copyright © 2002-2003 GBDI-ICMC-USP