stBasicArrayObject< DataType, OIDType > Class Template Reference
GBDI Arboretum
Version Release 1
stBasicArrayObject< DataType, OIDType > Class Template Reference
#include <stBasicObjects.h>
Public Member Functions
stBasicArrayObject ()
stBasicArrayObject (stSize n, const DataType *data=NULL)
virtual ~stBasicArrayObject ()
void SetData (const DataType *data)
DataType * GetData ()
stSize GetSize ()
DataType & operator[] (int idx)
DataType Get (stCount idx)
long GetOID ()
void SetOID (OIDType oid)
stBasicArrayObject * Clone ()
stSize GetSerializedSize ()
const stByte * Serialize ()
void Unserialize (const stByte *data, stSize dataSize)
bool IsEqual (stObject *obj)
Public Member Functions inherited from stObject
stObject ()
Detailed Description
template<class DataType, class OIDType = int>
class stBasicArrayObject< DataType, OIDType >
This class template implements an array object that can be indexed by all metric trees in this library.
This object holds an array of some type and its OID. The OID may be used to hold an additional information about the object (like the primary key in a database) and will never be used by the distance functions.
The template parameter DataType defines the data type of each unit of the array. It may be any C/C++ standard numeric types (integers, characters and floating points). The template parameter OIDType defines the type of the OID to be used. As DataType, it may assume any numeric type. By default, it will always be and int value.
The Serialized version of this class is organized as follows:
I'll provide the figure later...
This class template was designed to work with the metric evaluators defined in stBasicMetricEvaluators.h.
Version
1.1
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
See also
stObject
Todo:
Documentation review.
It needs optimizations.
Definition at line 112 of file stBasicObjects.h.
Constructor & Destructor Documentation
template<class DataType , class OIDType = int> stBasicArrayObject< DataType, OIDType >::stBasicArrayObject () inline
Default constructor. It creates an array with 0 elements. Use SetSize() to change the number of entries before use this instance.
This constructor is required by the stObject interface.
Definition at line 120 of file stBasicObjects.h.
Referenced by stBasicArrayObject< DataType, OIDType >::Clone().
template<class DataType , class OIDType = int> stBasicArrayObject< DataType, OIDType >::stBasicArrayObject (stSize n, const DataType * data = NULL) inline
Creates a new instance of this class with n entries. If the parameter data is not NULL, the content pointed by it will be used to initializate this instance.
Parameters
n Number of entries.
data The initial values of NULL (default).
Definition at line 135 of file stBasicObjects.h.
References stBasicArrayObject< DataType, OIDType >::SetData().
template<class DataType , class OIDType = int> virtual stBasicArrayObject< DataType, OIDType >::~stBasicArrayObject () inline virtual
Disposes this instance and releases all associated resources.
Definition at line 153 of file stBasicObjects.h.
Member Function Documentation
template<class DataType , class OIDType = int> stBasicArrayObject* stBasicArrayObject< DataType, OIDType >::Clone () inline virtual
This method must create a clone (copy) of this class. The new instance must have the same behaviour of the original instance but can not keep any links to its creator (they are independent). In other words, the clone will not reflect any changes done in the original class.
Returns
The clone (copy) of this object.
Note
This method is required to fulfil the stObject interface.
Implements stObject.
Definition at line 233 of file stBasicObjects.h.
References stBasicArrayObject< DataType, OIDType >::GetOID(), stBasicArrayObject< DataType, OIDType >::SetOID(), and stBasicArrayObject< DataType, OIDType >::stBasicArrayObject().
template<class DataType , class OIDType = int> DataType stBasicArrayObject< DataType, OIDType >::Get (stCount idx)
Gets the value of the element at a given position.
Parameters
idx The index of the desired entry.
Exceptions
out_of_range If the index is out of range.
template<class DataType , class OIDType = int> DataType* stBasicArrayObject< DataType, OIDType >::GetData () inline
Returns the pointer to the data array.
Definition at line 174 of file stBasicObjects.h.
template<class DataType , class OIDType = int> long stBasicArrayObject< DataType, OIDType >::GetOID () inline virtual
Returns the OID associated with this instance.
Warning
This method returns nothing if the object size is 0.
Reimplemented from stObject.
Definition at line 209 of file stBasicObjects.h.
Referenced by stBasicArrayObject< DataType, OIDType >::Clone().
template<class DataType , class OIDType = int> stSize stBasicArrayObject< DataType, OIDType >::GetSerializedSize () inline virtual
This method must return the size of the serialized version of this object in bytes.
See also
Serialize()
Unserialize()
Note
This method is required to fulfil the stObject interface.
Implements stObject.
Definition at line 242 of file stBasicObjects.h.
template<class DataType , class OIDType = int> stSize stBasicArrayObject< DataType, OIDType >::GetSize () inline
Returns the number of the elements of this array.
Definition at line 181 of file stBasicObjects.h.
template<class DataType , class OIDType = int> bool stBasicArrayObject< DataType, OIDType >::IsEqual (stObject * obj) virtual
This method must return True if the object in parameter is equal (has the same content) of the object that call it.
Parameters
obj Object that will be used in comparison.
Returns
whether the obj has the same content.
See also
Clone()
Note
This method is required to fulfil the stObject interface.
Implements stObject.
template<class DataType , class OIDType = int> DataType& stBasicArrayObject< DataType, OIDType >::operator[] (int idx) inline
This operator can be used to access all positions of the array for reading or writing.
Parameters
idx The index of the element.
Warning
This operator does not check the range of idx.
Definition at line 192 of file stBasicObjects.h.
template<class DataType , class OIDType = int> const stByte* stBasicArrayObject< DataType, OIDType >::Serialize () inline virtual
This method must create a serialized version of this instance. The serialized version is an array of bytes that will hold all information required to rebuild this object. For example, if the object is a string, the serialized form may be the string itself without the terminator character (since it is a sequence of bytes).
This array will be used by the SlimTree to store the object into a disk page and to recover it (by calling Unserialize()) and its size given by GetSerializedSize().
The effect of the of A->Unserialize(B->Serialize(), B->GetSerializedSize()) must be the same of A=B->Clone().
Implementation note: The SlimTree will not claim the ownership of the returned array. The object must dispose it when it is not required. In case of the serialized version be a pointer to an internal array, no copy operation will be necessary.
Returns
The serialized version of this object.
See also
GetSerializedSize()
Unserialized()
Note
This method is required to fulfil the stObject interface.
Implements stObject.
Definition at line 249 of file stBasicObjects.h.
template<class DataType , class OIDType = int> void stBasicArrayObject< DataType, OIDType >::SetData (const DataType * data) inline
Copies the content of the array data to this object. The array pointed by data must have at least GetSize() entries.
Parameters
data The array with the values.
Definition at line 166 of file stBasicObjects.h.
Referenced by stBasicArrayObject< DataType, OIDType >::stBasicArrayObject().
template<class DataType , class OIDType = int> void stBasicArrayObject< DataType, OIDType >::SetOID (OIDType oid) inline
Sets the OID associated with this instance.
Parameters
oid The new OID value.
Warning
This method does nothing if the object size is 0.
Definition at line 223 of file stBasicObjects.h.
Referenced by stBasicArrayObject< DataType, OIDType >::Clone().
template<class DataType , class OIDType = int> void stBasicArrayObject< DataType, OIDType >::Unserialize (const stByte * data, stSize dataSize) inline virtual
This method must rebuild the object from its serialized version. The serialized version is an array of bytes that holds all information required to rebuild an object. For example, if the object is a string, the serialized form may be the string itself without the terminator character (since it is a sequence of bytes).
This method will be used by the SlimTree to rebuild the object to compare it with another object (the sample object in a query or another rebuilt object).
The effect of the of A->Unserialize(B->Serialize(), B->GetSerializedSize()) must be the same of A=B->Clone().
Implementation note: The SlimTree is the owner of the data array. This means that this array may vanish at any time after the call of Unserialize(). There is also another restriction. The Unserialize() method must never modify the contents of the data array.
Parameters
data The serialized object.
datasize The size (in bytes) of the data array.
See also
Serialized()
Note
This method is required to fulfil the stObject interface.
Implements stObject.
Definition at line 256 of file stBasicObjects.h.
The documentation for this class was generated from the following file:
stBasicObjects.h
Copyright © 2002-2003 GBDI-ICMC-USP