stBasicStringObject< DataType, OIDType > Class Template Reference
GBDI Arboretum
Version Release 1
stBasicStringObject< DataType, OIDType > Class Template Reference
#include <stBasicObjects.h>
Public Member Functions
stBasicStringObject ()
stBasicStringObject (const DataType *str)
stBasicStringObject (stBasicStringObject *str)
virtual ~stBasicStringObject ()
stSize GetSize ()
stSize GetLength ()
DataType & operator[] (int idx)
DataType Get (int idx)
OIDType GetOID ()
void SetOID (OIDType oid)
void SetString (const DataType *str)
const DataType * GetString ()
stBasicStringObject * Clone ()
stSize GetSerializedSize ()
const stByte * Serialize ()
void Unserialize (const stByte *data, stSize dataSize)
bool IsEqual (stBasicStringObject *obj)
Detailed Description
template<class DataType, class OIDType = int>
class stBasicStringObject< DataType, OIDType >
This class template implements an string object that can be indexed by all metric trees in this library.
This object holds a null terminated string of some type and a OID. The OID may be used to hold an additional information about the object (like the primary key in a database) and will never be used by the distance functions.
The template parameter DataType defines the data type of each unit of the array. It may be any C/C++ standard numeric types (integers, characters and floating points). The template parameter OIDType defines the type of the OID to be used. As DataType, it may assume any numeric type. By default, it will always be and int value.
The Serialized version of this class is organized as follows:
+--—+---—+
| OID | Data |
+--—+---—+
Since Data has a variable size (associated with the string object), the serialized form will also have a variable number of bytes.
This class template was designed to work with the metric evaluators defined in stBasicMetricEvaluators.h.
Version
1.0
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
See also
stObject
Definition at line 352 of file stBasicObjects.h.
Constructor & Destructor Documentation
template<class DataType , class OIDType = int> stBasicStringObject< DataType, OIDType >::stBasicStringObject () inline
Default constructor. It creates an array with 0 elements. Use SetSize() to change the number of entries before use this instance.
This constructor is required by the stObject interface.
Definition at line 360 of file stBasicObjects.h.
Referenced by stBasicStringObject< DataType, OIDType >::Clone().
template<class DataType , class OIDType = int> stBasicStringObject< DataType, OIDType >::stBasicStringObject (const DataType * str) inline
Creates a new instance of this class and initializes it with a given null terminated string.
Parameters
str A null terminated string.
Definition at line 374 of file stBasicObjects.h.
References stBasicStringObject< DataType, OIDType >::SetString().
template<class DataType , class OIDType = int> stBasicStringObject< DataType, OIDType >::stBasicStringObject (stBasicStringObject< DataType, OIDType > * str) inline
Creates a new instance of this class and initializes it with a given null terminated string.
Parameters
str A null terminated string.
Definition at line 391 of file stBasicObjects.h.
template<class DataType , class OIDType = int> virtual stBasicStringObject< DataType, OIDType >::~stBasicStringObject () inline virtual
Disposes this instance and releases all associated resources.
Definition at line 405 of file stBasicObjects.h.
Member Function Documentation
template<class DataType , class OIDType = int> stBasicStringObject* stBasicStringObject< DataType, OIDType >::Clone () inline
This method must create a clone (copy) of this class. The new instance must have the same behaviour of the original instance but can not keep any links to its creator (they are independent). In other words, the clone will not reflect any changes done in the original class.
Returns
The clone (copy) of this object.
Note
This method is required to fulfil the stObject interface.
Definition at line 506 of file stBasicObjects.h.
References stBasicStringObject< DataType, OIDType >::GetOID(), stBasicStringObject< DataType, OIDType >::SetOID(), and stBasicStringObject< DataType, OIDType >::stBasicStringObject().
template<class DataType , class OIDType = int> DataType stBasicStringObject< DataType, OIDType >::Get (int idx) inline
Gets the value of the element at a given position.
Parameters
idx The index of the desired entry.
Exceptions
out_of_range If the index is out of range.
Definition at line 444 of file stBasicObjects.h.
template<class DataType , class OIDType = int> stSize stBasicStringObject< DataType, OIDType >::GetLength () inline
Returns the length of this string. It is a synonym to GetSize().
Definition at line 423 of file stBasicObjects.h.
template<class DataType , class OIDType = int> OIDType stBasicStringObject< DataType, OIDType >::GetOID () inline
Returns the OID associated with this instance.
Warning
This method returns nothing if the object size is 0.
Definition at line 457 of file stBasicObjects.h.
Referenced by stBasicStringObject< DataType, OIDType >::Clone().
template<class DataType , class OIDType = int> stSize stBasicStringObject< DataType, OIDType >::GetSerializedSize () inline
This method must return the size of the serialized version of this object in bytes.
See also
Serialize()
Unserialize()
Note
This method is required to fulfil the stObject interface.
Definition at line 515 of file stBasicObjects.h.
template<class DataType , class OIDType = int> stSize stBasicStringObject< DataType, OIDType >::GetSize () inline
Returns the length of this string. It is a synonym to GetLength(). This name is used by the basic metric evaluators templates.
Definition at line 416 of file stBasicObjects.h.
template<class DataType , class OIDType = int> const DataType* stBasicStringObject< DataType, OIDType >::GetString () inline
Returns the contents of this object as a null terminated string.
Warning
This method is meaningless if the contents of this instance is not a null terminated string.
See also
SetString()
Definition at line 498 of file stBasicObjects.h.
template<class DataType , class OIDType = int> bool stBasicStringObject< DataType, OIDType >::IsEqual (stBasicStringObject< DataType, OIDType > * obj)
This method must return True if the object in parameter is equal (has the same content) of the object that call it.
Parameters
obj Object that will be used in comparison.
Returns
whether the obj has the same content.
See also
Clone()
Note
This method is required to fulfil the stObject interface.
template<class DataType , class OIDType = int> DataType& stBasicStringObject< DataType, OIDType >::operator[] (int idx) inline
This operator can be used to access all positions of the array for reading or writing.
Parameters
idx The index of the element.
Warning
This operator does not check the range of idx.
Definition at line 434 of file stBasicObjects.h.
template<class DataType , class OIDType = int> const stByte* stBasicStringObject< DataType, OIDType >::Serialize () inline
This method must create a serialized version of this instance. The serialized version is an array of bytes that will hold all information required to rebuild this object. For example, if the object is a string, the serialized form may be the string itself without the terminator character (since it is a sequence of bytes).
This array will be used by the SlimTree to store the object into a disk page and to recover it (by calling Unserialize()) and its size given by GetSerializedSize().
The effect of the of A->Unserialize(B->Serialize(), B->GetSerializedSize()) must be the same of A=B->Clone().
Implementation note: The SlimTree will not claim the ownership of the returned array. The object must dispose it when it is not required. In case of the serialized version be a pointer to an internal array, no copy operation will be necessary.
Returns
The serialized version of this object.
See also
GetSerializedSize()
Unserialized()
Note
This method is required to fulfil the stObject interface.
Definition at line 522 of file stBasicObjects.h.
template<class DataType , class OIDType = int> void stBasicStringObject< DataType, OIDType >::SetOID (OIDType oid) inline
Sets the OID associated with this instance.
Parameters
OID The new OID value.
Warning
This method does nothing if the object size is 0.
Definition at line 472 of file stBasicObjects.h.
Referenced by stBasicStringObject< DataType, OIDType >::Clone().
template<class DataType , class OIDType = int> void stBasicStringObject< DataType, OIDType >::SetString (const DataType * str) inline
Copies a null terminated string to this instance.
Parameters
str A null terminates string.
See also
GetString()
Definition at line 484 of file stBasicObjects.h.
Referenced by stBasicStringObject< DataType, OIDType >::stBasicStringObject().
template<class DataType , class OIDType = int> void stBasicStringObject< DataType, OIDType >::Unserialize (const stByte * data, stSize dataSize) inline
This method must rebuild the object from its serialized version. The serialized version is an array of bytes that holds all information required to rebuild an object. For example, if the object is a string, the serialized form may be the string itself without the terminator character (since it is a sequence of bytes).
This method will be used by the SlimTree to rebuild the object to compare it with another object (the sample object in a query or another rebuilt object).
The effect of the of A->Unserialize(B->Serialize(), B->GetSerializedSize()) must be the same of A=B->Clone().
Implementation note: The SlimTree is the owner of the data array. This means that this array may vanish at any time after the call of Unserialize(). There is also another restriction. The Unserialize() method must never modify the contents of the data array.
Parameters
data The serialized object.
datasize The size (in bytes) of the data array.
See also
Serialized()
Note
This method is required to fulfil the stObject interface.
Definition at line 529 of file stBasicObjects.h.
The documentation for this class was generated from the following file:
stBasicObjects.h
Copyright © 2002-2003 GBDI-ICMC-USP