stDFLogicNode< ObjectType, EvaluatorType > Class Template Reference
GBDI Arboretum
Version Release 1
stDFLogicNode< ObjectType, EvaluatorType > Class Template Reference
#include <stDFTree.h>
Public Types
typedef stDFGlobalRep< ObjectType, EvaluatorType > tGR
Public Member Functions
stDFLogicNode (stCount maxOccupation)
~stDFLogicNode ()
int AddEntry (ObjectType *obj)
int AddEntry (stSize size, const stByte *object)
stCount GetNumberOfEntries ()
ObjectType * GetObject (stCount idx)
ObjectType * operator[] (stCount idx)
stPageID GetPageID (stCount idx)
stSize GetNEntries (stCount idx)
stDistance GetRadius (stCount idx)
void SetEntry (stCount idx, stPageID pageID, stSize nEntries, stDistance radius, stDistance *fieldDistance)
void AddIndexNode (stDFIndexNode *node)
void AddLeafNode (stDFLeafNode *node)
stCount GetRepresentativeIndex (stCount idx)
ObjectType * GetRepresentative (stCount idx)
void SetRepresentative (stCount rep0, stCount rep1)
int Distribute (stDFIndexNode *node0, ObjectType *&rep0, stDFIndexNode *node1, ObjectType *&rep1, EvaluatorType *metricEvaluator, tGR *GR)
int Distribute (stDFLeafNode *node0, ObjectType *&rep0, stDFLeafNode *node1, ObjectType *&rep1, EvaluatorType *metricEvaluator, tGR *GR)
int TestDistribution (stDFIndexNode *node0, stDFIndexNode *node1, EvaluatorType *metricEvaluator)
int TestDistribution (stDFLeafNode *node0, stDFLeafNode *node1, EvaluatorType *metricEvaluator)
void SetMinOccupation (stCount min)
stNodeType GetNodeType ()
void SetNodeType (stNodeType type)
bool IsRepresentative (stCount idx)
ObjectType * BuyObject (stCount idx)
stDistance * GetFieldDistance (stCount idx)
void SetFocusDistance (stCount idx, stCount iGlobalRep, stDistance iFieldDistance)
void SetFieldDistance (stCount idx, stDistance *fieldDistance)
Detailed Description
template<class ObjectType, class EvaluatorType>
class stDFLogicNode< ObjectType, EvaluatorType >
Thic class template represents a DFTree logic node entry. It is used to hold an index node or a leaf node in a memory form which allows better way to manipulate entries. It also implements means to distribute its contents between 2 nodes.
Each entry of this node can hold all information required by both nodes at same time so, the users of this node must control if it holds an index node or a leaf node.
Warning
This node will take the ownership of all object instances added to this node. It means that the object instance will be destroyed by the destructor of this class.
Version
1.0
Date
2005/03/08 19:43:09
Author
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Joselene Marques (josel.nosp@m.ene@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Todo:
Documentation review.
More tests!
Definition at line 125 of file stDFTree.h.
Member Typedef Documentation
template<class ObjectType , class EvaluatorType > typedef stDFGlobalRep<ObjectType, EvaluatorType> stDFLogicNode< ObjectType, EvaluatorType >::tGR
This type implements the GR.
Definition at line 132 of file stDFTree.h.
Constructor & Destructor Documentation
template<class ObjectType , class EvaluatorType > stDFLogicNode< ObjectType, EvaluatorType >::stDFLogicNode (stCount maxOccupation)
Creates a new instance of this node with no objects.
Parameters
maxOccupation The maximum number of entries.
template<class ObjectType , class EvaluatorType > stDFLogicNode< ObjectType, EvaluatorType >::~stDFLogicNode ()
Disposes this instance and releases all related resources. All instances of object added to this node will also be deleted unless it is not owned by this node (see method BuyObject()).
Member Function Documentation
template<class ObjectType , class EvaluatorType > int stDFLogicNode< ObjectType, EvaluatorType >::AddEntry (ObjectType * obj) inline
Adds an object to this node. This method will claim the ownership of the object instance.
Use SetEntry() to fill the other fields of each entry.
Parameters
obj The object to be added.
Returns
The entry id or -1 for error.
Definition at line 157 of file stDFTree.h.
References STFOCUS.
template<class ObjectType , class EvaluatorType > int stDFLogicNode< ObjectType, EvaluatorType >::AddEntry (stSize size, const stByte * object)
Adds an object to this node.
Use SetEntry() to fill the other fields of each entry.
Parameters
size The size of the object in bytes.
object The object data.
Returns
The entry id or -1 for error.
template<class ObjectType , class EvaluatorType > void stDFLogicNode< ObjectType, EvaluatorType >::AddIndexNode (stDFIndexNode * node)
Adds all objects of an index node. It will also set the node type to stDFNode::INDEX.
Parameters
node The node.
template<class ObjectType , class EvaluatorType > void stDFLogicNode< ObjectType, EvaluatorType >::AddLeafNode (stDFLeafNode * node)
Adds all objects of a leaf node. It will also set the node type to stDFNode::LEAF.
Parameters
node The node.
template<class ObjectType , class EvaluatorType > ObjectType* stDFLogicNode< ObjectType, EvaluatorType >::BuyObject (stCount idx) inline
Gets the ownership of an object associated with a given entry. This method will avoid the automatic destruction of the object instance by the destructor of this node.
This method can be used to buy the representative objects to avoid unnecessary replications.
Parameters
idx The object index.
Returns
The pointer to the object.
Definition at line 425 of file stDFTree.h.
Referenced by stDFLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > int stDFLogicNode< ObjectType, EvaluatorType >::Distribute (stDFIndexNode * node0, ObjectType *& rep0, stDFIndexNode * node1, ObjectType *& rep1, EvaluatorType * metricEvaluator, tGR * GR) inline
Distribute objects between 2 index nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
rep0 Representative of node 0.
node1 The second node.
rep0 Representative of node 1.
metricEvaluator The metric evaluator to be used to compute distances.
GR Used to know when find GR
Returns
The number of computed distances.
Definition at line 306 of file stDFTree.h.
References stDFLogicNode< ObjectType, EvaluatorType >::BuyObject(), stDFLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex(), and stDFLogicNode< ObjectType, EvaluatorType >::TestDistribution().
template<class ObjectType , class EvaluatorType > int stDFLogicNode< ObjectType, EvaluatorType >::Distribute (stDFLeafNode * node0, ObjectType *& rep0, stDFLeafNode * node1, ObjectType *& rep1, EvaluatorType * metricEvaluator, tGR * GR) inline
Distribute objects between 2 leaf nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
rep0 Representative of node 0.
node1 The second node.
rep1 Representative of node 1.
metricEvaluator The metric evaluator to be used to compute distances.
GR Used to know when find GR
Returns
The number of computed distances.
Definition at line 334 of file stDFTree.h.
References stDFLogicNode< ObjectType, EvaluatorType >::BuyObject(), stDFLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex(), and stDFLogicNode< ObjectType, EvaluatorType >::TestDistribution().
template<class ObjectType , class EvaluatorType > stDistance* stDFLogicNode< ObjectType, EvaluatorType >::GetFieldDistance (stCount idx) inline
Returns the GR of a given entry.
Parameters
idx The object index.
Returns
The vector with the GR
Definition at line 436 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > stSize stDFLogicNode< ObjectType, EvaluatorType >::GetNEntries (stCount idx) inline
Returns the number of entries in the sub-tree of a given entry. Only index nodes will use this field.
Parameters
idx The object index.
Definition at line 216 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > stNodeType stDFLogicNode< ObjectType, EvaluatorType >::GetNodeType () inline
Returns the node type. It may assume the values stDFNode::INDEX or stDFNode::LEAF.
Definition at line 393 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > stCount stDFLogicNode< ObjectType, EvaluatorType >::GetNumberOfEntries () inline
Returns the number of entries in this node.
Definition at line 179 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stDFLogicNode< ObjectType, EvaluatorType >::GetObject (stCount idx) inline
Returns the object of a given entry.
Parameters
idx The object index.
Definition at line 188 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > stPageID stDFLogicNode< ObjectType, EvaluatorType >::GetPageID (stCount idx) inline
Returns the PageID of a given entry. Only index nodes will use this field.
Parameters
idx The object index.
Definition at line 206 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > stDistance stDFLogicNode< ObjectType, EvaluatorType >::GetRadius (stCount idx) inline
Returns the radius of the sub-tree of a given entry. Only index nodes will use this field.
Parameters
idx The object index.
Definition at line 226 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stDFLogicNode< ObjectType, EvaluatorType >::GetRepresentative (stCount idx) inline
Returns the representative object.
Parameters
id The representative ID. It may be 0 or 1.
Definition at line 277 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > stCount stDFLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex (stCount idx) inline
Returns the id of the representative object.
Parameters
id The representative ID. It may be 0 or 1.
Definition at line 268 of file stDFTree.h.
Referenced by stDFLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > bool stDFLogicNode< ObjectType, EvaluatorType >::IsRepresentative (stCount idx) inline
Verifies if a given object is a representative.
Parameters
idx Object index.
Returns
True if the object is a representative or false otherwise.
Definition at line 410 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stDFLogicNode< ObjectType, EvaluatorType >::operator[] (stCount idx) inline
Returns the object of a given entry.
Parameters
idx The object index.
Definition at line 197 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > void stDFLogicNode< ObjectType, EvaluatorType >::SetEntry (stCount idx, stPageID pageID, stSize nEntries, stDistance radius, stDistance * fieldDistance) inline
Sets the data associated with a given entry.
Parameters
idx The object index.
pageID The pageID.
nEntries The number of entries in the sub-tree.
radius The radius of the sub-tree.
FieldDistance The distance from object to GR
Definition at line 239 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > void stDFLogicNode< ObjectType, EvaluatorType >::SetFieldDistance (stCount idx, stDistance * fieldDistance) inline
Set GR of a given entry.
Parameters
idx The object index.
FieldDistance The GR Vector
Definition at line 457 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > void stDFLogicNode< ObjectType, EvaluatorType >::SetFocusDistance (stCount idx, stCount iGlobalRep, stDistance iFieldDistance) inline
Sets the Focus Distance.
Parameters
idx The object index.
iGlobalRep The GlobalRep index.
FieldDistance The distance to GlobalRep index.
Definition at line 447 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > void stDFLogicNode< ObjectType, EvaluatorType >::SetMinOccupation (stCount min) inline
Set minimum occupation. This must be the minimum number of objects in a page. This value must be at least 1.
Definition at line 381 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > void stDFLogicNode< ObjectType, EvaluatorType >::SetNodeType (stNodeType type) inline
Sets the node type.
Definition at line 400 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > void stDFLogicNode< ObjectType, EvaluatorType >::SetRepresentative (stCount rep0, stCount rep1) inline
Sets both representatives ids. Use UpdateDistances() to update all distances between objects and.
Parameters
rep0 Index of representative 0.
rep1 Index of representative 1.
Definition at line 288 of file stDFTree.h.
template<class ObjectType , class EvaluatorType > int stDFLogicNode< ObjectType, EvaluatorType >::TestDistribution (stDFIndexNode * node0, stDFIndexNode * node1, EvaluatorType * metricEvaluator)
Tests the distribution of objects between 2 index nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
node1 The second node.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
Warning
Since it is just a test fnction, it will not inialize the fields of the entries.
Referenced by stDFLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > int stDFLogicNode< ObjectType, EvaluatorType >::TestDistribution (stDFLeafNode * node0, stDFLeafNode * node1, EvaluatorType * metricEvaluator)
Tests the distribution of objects between 2 leaf nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
node1 The second node.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
The documentation for this class was generated from the following file:
stDFTree.h
Copyright © 2002-2003 GBDI-ICMC-USP