stSlimLogicNode< ObjectType, EvaluatorType > Class Template Reference
GBDI Arboretum
Version Release 1
stSlimLogicNode< ObjectType, EvaluatorType > Class Template Reference
#include <stSlimTree.h>
Public Member Functions
stSlimLogicNode (stCount maxOccupation)
~stSlimLogicNode ()
int AddEntry (ObjectType *obj)
int AddEntry (stSize size, const stByte *object)
stCount GetNumberOfEntries ()
ObjectType * GetObject (int idx)
ObjectType * operator[] (int idx)
stPageID GetPageID (int idx)
stSize GetNEntries (int idx)
stDistance GetRadius (int idx)
void SetEntry (int idx, stPageID pageID, stSize nEntries, stDistance radius)
void AddIndexNode (stSlimIndexNode *node)
void AddLeafNode (stSlimLeafNode *node)
stCount GetRepresentativeIndex (stCount idx)
ObjectType * GetRepresentative (stCount idx)
void SetRepresentative (stCount rep0, stCount rep1)
stCount Distribute (stSlimIndexNode *node0, ObjectType *&rep0, stSlimIndexNode *node1, ObjectType *&rep1, EvaluatorType *metricEvaluator)
stCount Distribute (stSlimLeafNode *node0, ObjectType *&rep0, stSlimLeafNode *node1, ObjectType *&rep1, EvaluatorType *metricEvaluator)
stCount TestDistribution (stSlimIndexNode *node0, stSlimIndexNode *node1, EvaluatorType *metricEvaluator)
stCount TestDistribution (stSlimLeafNode *node0, stSlimLeafNode *node1, EvaluatorType *metricEvaluator)
void SetMinOccupation (stCount min)
stNodeType GetNodeType ()
void SetNodeType (stNodeType type)
bool IsRepresentative (stCount idx)
ObjectType * BuyObject (stCount idx)
Detailed Description
template<class ObjectType, class EvaluatorType>
class stSlimLogicNode< ObjectType, EvaluatorType >
Thic class template represents a SlimTree logic node entry. It is used to hold an index node or a leaf node in a memory form which allows better way to manipulate entries. It also implements means to distribute its contents between 2 nodes.
Each entry of this node can hold all information required by both nodes at same time so, the users of this node must control if it holds an index node or a leaf node.
Warning
This node will take the ownership of all object instances added to this node. It means that the object instance will be destroyed by the destructor of this class.
Version
1.0
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.sc..nosp@m.usp..nosp@m.br)
Todo:
Documentation review.
Tests!
Definition at line 120 of file stSlimTree.h.
Constructor & Destructor Documentation
template<class ObjectType , class EvaluatorType > stSlimLogicNode< ObjectType, EvaluatorType >::stSlimLogicNode (stCount maxOccupation)
Creates a new instance of this node with no objects.
Parameters
maxOccupation The maximum number of entries.
template<class ObjectType , class EvaluatorType > stSlimLogicNode< ObjectType, EvaluatorType >::~stSlimLogicNode ()
Disposes this instance and releases all related resources. All instances of object added to this node will also be deleted unless it is not owned by this node (see method BuyObject()).
Member Function Documentation
template<class ObjectType , class EvaluatorType > int stSlimLogicNode< ObjectType, EvaluatorType >::AddEntry (ObjectType * obj) inline
Adds an object to this node. This method will claim the ownership of the object instance.
Use SetEntry() to fill the other fields of each entry.
Parameters
obj The object to be added.
Returns
The entry id or -1 for error.
Definition at line 145 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > int stSlimLogicNode< ObjectType, EvaluatorType >::AddEntry (stSize size, const stByte * object)
Adds an object to this node.
Use SetEntry() to fill the other fields of each entry.
Parameters
size The size of the object in bytes.
object The object data.
Returns
The entry id or -1 for error.
template<class ObjectType , class EvaluatorType > void stSlimLogicNode< ObjectType, EvaluatorType >::AddIndexNode (stSlimIndexNode * node)
Adds all objects of an index node. It will also set the node type to stSlimNode::INDEX.
Parameters
node The node.
template<class ObjectType , class EvaluatorType > void stSlimLogicNode< ObjectType, EvaluatorType >::AddLeafNode (stSlimLeafNode * node)
Adds all objects of a leaf node. It will also set the node type to stSlimNode::LEAF.
Parameters
node The node.
template<class ObjectType , class EvaluatorType > ObjectType* stSlimLogicNode< ObjectType, EvaluatorType >::BuyObject (stCount idx) inline
Gets the ownership of an object associated with a given entry. This method will avoid the automatic destruction of the object instance by the destructor of this node.
This method can be used to buy the representative objects to avoid unnecessary replications.
Parameters
idx The object index.
Returns
The pointer to the object.
Definition at line 405 of file stSlimTree.h.
Referenced by stSlimLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > stCount stSlimLogicNode< ObjectType, EvaluatorType >::Distribute (stSlimIndexNode * node0, ObjectType *& rep0, stSlimIndexNode * node1, ObjectType *& rep1, EvaluatorType * metricEvaluator) inline
Distribute objects between 2 index nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
rep0 Representative of node 0.
node1 The second node.
rep0 Representative of node 1.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
Definition at line 287 of file stSlimTree.h.
References stSlimLogicNode< ObjectType, EvaluatorType >::BuyObject(), stSlimLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex(), and stSlimLogicNode< ObjectType, EvaluatorType >::TestDistribution().
template<class ObjectType , class EvaluatorType > stCount stSlimLogicNode< ObjectType, EvaluatorType >::Distribute (stSlimLeafNode * node0, ObjectType *& rep0, stSlimLeafNode * node1, ObjectType *& rep1, EvaluatorType * metricEvaluator) inline
Distribute objects between 2 leaf nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
rep0 Representative of node 0.
node1 The second node.
rep1 Representative of node 1.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
Definition at line 314 of file stSlimTree.h.
References stSlimLogicNode< ObjectType, EvaluatorType >::BuyObject(), stSlimLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex(), and stSlimLogicNode< ObjectType, EvaluatorType >::TestDistribution().
template<class ObjectType , class EvaluatorType > stSize stSlimLogicNode< ObjectType, EvaluatorType >::GetNEntries (int idx) inline
Returns the number of entries in the sub-tree of a given entry. Only index nodes will use this field.
Parameters
idx The object index.
Definition at line 202 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > stNodeType stSlimLogicNode< ObjectType, EvaluatorType >::GetNodeType () inline
Returns the node type. It may assume the values stSlimNode::INDEX or stSlimNode::LEAF.
Definition at line 373 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > stCount stSlimLogicNode< ObjectType, EvaluatorType >::GetNumberOfEntries () inline
Returns the number of entries in this node.
Definition at line 166 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stSlimLogicNode< ObjectType, EvaluatorType >::GetObject (int idx) inline
Returns the object of a given entry.
Parameters
idx The object index.
Definition at line 175 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > stPageID stSlimLogicNode< ObjectType, EvaluatorType >::GetPageID (int idx) inline
Returns the PageID of a given entry. Only index nodes will use this field.
Parameters
idx The object index.
Definition at line 193 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > stDistance stSlimLogicNode< ObjectType, EvaluatorType >::GetRadius (int idx) inline
Returns the radius of the sub-tree of a given entry. Only index nodes will use this field.
Parameters
idx The object index.
Definition at line 211 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stSlimLogicNode< ObjectType, EvaluatorType >::GetRepresentative (stCount idx) inline
Returns the representative object.
Parameters
idx The representative ID. It may be 0 or 1.
Definition at line 259 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > stCount stSlimLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex (stCount idx) inline
Returns the idx of the representative object.
Parameters
idx The representative ID. It may be 0 or 1.
Definition at line 250 of file stSlimTree.h.
Referenced by stSlimLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > bool stSlimLogicNode< ObjectType, EvaluatorType >::IsRepresentative (stCount idx) inline
Verifies if a given object is a representative.
Parameters
idx Object index.
Returns
True if the object is a representative or false otherwise.
Definition at line 390 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stSlimLogicNode< ObjectType, EvaluatorType >::operator[] (int idx) inline
Returns the object of a given entry.
Parameters
idx The object index.
Definition at line 184 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > void stSlimLogicNode< ObjectType, EvaluatorType >::SetEntry (int idx, stPageID pageID, stSize nEntries, stDistance radius) inline
Sets the data associated with a given entry.
Parameters
idx The object index.
pageID The pageID.
nEntries The number of entries in the sub-tree.
radius The radius of the sub-tree.
Definition at line 223 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > void stSlimLogicNode< ObjectType, EvaluatorType >::SetMinOccupation (stCount min) inline
Set minimum occupation. This must be the minimum number of objects in a page. This value must be at least 1.
Definition at line 361 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > void stSlimLogicNode< ObjectType, EvaluatorType >::SetNodeType (stNodeType type) inline
Sets the node type.
Definition at line 380 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > void stSlimLogicNode< ObjectType, EvaluatorType >::SetRepresentative (stCount rep0, stCount rep1) inline
Sets both representatives ids. Use UpdateDistances() to update all distances between objects and.
Parameters
rep0 Index of representative 0.
rep1 Index of representative 1.
Definition at line 270 of file stSlimTree.h.
template<class ObjectType , class EvaluatorType > stCount stSlimLogicNode< ObjectType, EvaluatorType >::TestDistribution (stSlimIndexNode * node0, stSlimIndexNode * node1, EvaluatorType * metricEvaluator)
Tests the distribution of objects between 2 index nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
node1 The second node.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
Warning
Since it is just a test fnction, it will not inialize the fields of the entries.
Referenced by stSlimLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > stCount stSlimLogicNode< ObjectType, EvaluatorType >::TestDistribution (stSlimLeafNode * node0, stSlimLeafNode * node1, EvaluatorType * metricEvaluator)
Tests the distribution of objects between 2 leaf nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
node1 The second node.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
The documentation for this class was generated from the following file:
stSlimTree.h
Copyright © 2002-2003 GBDI-ICMC-USP