stPageServer Class Reference
GBDI Arboretum
Version Release 1
stPageServer Class Reference abstract
#include <stPageServer.h>
Public Member Functions
virtual stPage * GetPage (int clientID, stPageID pageid)=0
virtual void WritePage (int clientID, stPage *page)=0
virtual stPage * GetNewPage (int clientID)=0
virtual void DisposePage (int clientID, stPage *page)=0
virtual void ReleasePage (int clientID, stPage *page)=0
virtual stPageID GetHeaderPageID (int clientID)
virtual stSize GetPageCount (int clientID)
virtual stSize GetPageSize ()
Detailed Description
This class defines the abstract class stPageServer. A page server is a low-level block device interface that is used by stClientPageManager.
Version
1.0
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
See also
stClientPageManager
Definition at line 90 of file stPageServer.h.
Member Function Documentation
virtual void stPageServer::DisposePage (int clientID, stPage * page) pure virtual
Disposes a page.
Parameters
page The page.
Referenced by stClientPageManager::DisposePage().
virtual stPageID stPageServer::GetHeaderPageID (int clientID) virtual
virtual stPage* stPageServer::GetNewPage (int clientID) pure virtual
Creates a new page.
Returns
The new page.
Referenced by stClientPageManager::GetNewPage().
virtual stPage* stPageServer::GetPage (int clientID, stPageID pageid) pure virtual
Reads a page from a page server.
Parameters
pageid The id of the required page.
Returns
The given page.
Referenced by stClientPageManager::GetPage().
virtual stSize stPageServer::GetPageCount (int clientID) virtual
Referenced by stClientPageManager::IsEmpty().
virtual stSize stPageServer::GetPageSize () virtual
Referenced by stClientPageManager::GetMinimumPageSize().
virtual void stPageServer::ReleasePage (int clientID, stPage * page) pure virtual
Releases this page.
Parameters
page The page.
Referenced by stClientPageManager::ReleasePage().
virtual void stPageServer::WritePage (int clientID, stPage * page) pure virtual
Writes a page into a page server.
Parameters
page The page.
Referenced by stClientPageManager::WritePage().
The documentation for this class was generated from the following file:
stPageServer.h
Copyright © 2002-2003 GBDI-ICMC-USP