stDFLeafNode Class Reference
GBDI Arboretum
Version Release 1
stDFLeafNode Class Reference
#include <stDFNode.h>
Classes
struct stDFLeafEntry
Public Types
typedef struct stDFLeafNode::stDFLeafEntry stDFLeafEntry
Public Types inherited from stDFNode
enum stDFNodeType { INDEX = 0x4449, LEAF = 0x464C }
Public Member Functions
stDFLeafNode (stPage *page, bool create=false)
stDFLeafEntry & GetLeafEntry (stCount idx)
virtual int AddEntry (stSize size, const stByte *object)
int GetRepresentativeEntry ()
const stByte * GetObject (stCount idx)
stSize GetObjectSize (stCount idx)
void RemoveEntry (stCount idx)
virtual stDistance GetMinimumRadius ()
virtual stCount GetTotalObjectCount ()
stDistance * GetFieldDistance (stCount idx)
Public Member Functions inherited from stDFNode
virtual ~stDFNode ()
stNodeType GetNodeType ()
stPage * GetPage ()
stPageID GetPageID ()
stCount GetNumberOfEntries ()
void RemoveAll ()
Static Public Member Functions
static stSize GetLeafEntryOverhead ()
Static Public Member Functions inherited from stDFNode
static stDFNode * CreateNode (stPage *page)
static stSize GetGlobalOverhead ()
Additional Inherited Members
Protected Types inherited from stDFNode
typedef struct stDFNode::stDFNodeHeader stDFNodeHeader
Protected Member Functions inherited from stDFNode
stDFNode (stPage *page)
Protected Attributes inherited from stDFNode
stDFNodeHeader * Header
stPage * Page
Detailed Description
This class implements the Leaf node of the DFTree.
The DFTree leaf node... The structure of Leaf Node follows:
Leaf node structure
The Header holds the information about the node itself.
Type: Type of this node. It is always stDFNode::LEAF (0x464C).
Occupation: Number of entries in this node.
The Entry holds the information of the link to the other node.
Distance: The distance of this object from the representative object.
Offset: The offset of the object in the page. DO NOT MODIFY ITS VALUE.
The Object is an array of bytes that holds the information required to rebuild the original object.
Version
1.0
Author
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Todo:
Documentation review.
See also
stDFNode
stDFIndexNode
stDFMemLeafNode
Definition at line 529 of file stDFNode.h.
Member Typedef Documentation
typedef struct stDFLeafNode::stDFLeafEntry stDFLeafNode::stDFLeafEntry
This type represents a DF tree leaf node entry.
Constructor & Destructor Documentation
stDFLeafNode::stDFLeafNode (stPage * page, bool create = false)
Creates a new instance of this class. The paramenter page is an instance of stPage that hold the node data.
The parameter create tells to stLeafPage what operation will be performed. True means that the page will be initialized and false means that the page will be used as it is. The default value is false.
Parameters
page The page that hold the data of this node.
create The operation to be performed.
Member Function Documentation
virtual int stDFLeafNode::AddEntry (stSize size, const stByte * object) virtual
Adds a new entry to this node. This method will return the id of the new node or a negative value for failure.
This method will fail if there is not enough space to hold the new object.
If you have added a new entry successfully, you may edit the entry fields using the method GetEntry().
Parameters
size The size of the object in bytes.
object The object data.
Warning
The parameter size is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The position in the vector Entries.
See also
RemoveEntry()
GetEntry()
Implements stDFNode.
stDistance* stDFLeafNode::GetFieldDistance (stCount idx) inline
Returns the GR distance of a given entry.
Parameters
idx The object index.
Returns
The GR Vector
Definition at line 678 of file stDFNode.h.
References stDFLeafNode::stDFLeafEntry::FieldDistance.
stDFLeafEntry& stDFLeafNode::GetLeafEntry (stCount idx) inline
Returns the reference of the desired leaf entry. You may use this method to read and modify the leaf entry information.
Parameters
id The id of the leaf entry.
Warning
The parameter id is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
stLeafEntry the reference of the desired entry.
See also
stLeafEntry
GetNumberOfEntries()
GetObject()
GetObjectSize()
Definition at line 583 of file stDFNode.h.
References stDFNode::GetNumberOfEntries().
static stSize stDFLeafNode::GetLeafEntryOverhead () inline static
Returns the overhead of each leaf node entry in bytes.
Definition at line 668 of file stDFNode.h.
Referenced by stDFMemLeafNode< ObjectType >::CanAdd().
virtual stDistance stDFLeafNode::GetMinimumRadius () virtual
Returns the minimum radius of this node.
Implements stDFNode.
const stByte* stDFLeafNode::GetObject (stCount idx) virtual
Gets the serialized object. Use GetObjectSize() to determine the size of the object.
Parameters
id The id of the entry.
Warning
The parameter id is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
A pointer to the serialized object.
See also
GetObjectSize()
Implements stDFNode.
stSize stDFLeafNode::GetObjectSize (stCount idx) virtual
Returns the size of the object. Use GetObject() to get the object data.
Parameters
id The id of the entry.
Warning
The parameter id is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The size of the serialized object.
See also
GetObject()
Implements stDFNode.
int stDFLeafNode::GetRepresentativeEntry ()
Returns the entry id that hold the representative object.
virtual stCount stDFLeafNode::GetTotalObjectCount () inline virtual
Returns the total number of objects in the subtree.
Implements stDFNode.
Definition at line 661 of file stDFNode.h.
References stDFNode::GetNumberOfEntries().
void stDFLeafNode::RemoveEntry (stCount idx)
Removes an entry from this object.
Parameters
id The id of the entry.
Warning
The parameter id is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
A pointer to the serialized object.
See also
GetObjectSize()
Todo:
This method is not implemented yet.
The documentation for this class was generated from the following file:
stDFNode.h
Copyright © 2002-2003 GBDI-ICMC-USP