stMLogicNode< ObjectType, EvaluatorType > Class Template Reference
GBDI Arboretum
Version Release 1
stMLogicNode< ObjectType, EvaluatorType > Class Template Reference
#include <stMTree.h>
Public Member Functions
stMLogicNode (int maxOccupation)
~stMLogicNode ()
int AddEntry (ObjectType *obj)
int AddEntry (stSize size, const stByte *object)
int GetNumberOfEntries ()
ObjectType * GetObject (int idx)
ObjectType * operator[] (int idx)
stPageID GetPageID (int idx)
stDistance GetRadius (int idx)
void SetEntry (int idx, stPageID pageID, stDistance radius)
void AddIndexNode (stMIndexNode *node)
void AddLeafNode (stMLeafNode *node)
int GetRepresentativeIndex (int idx)
ObjectType * GetRepresentative (int idx)
void SetRepresentative (int rep0, int rep1)
int Distribute (stMIndexNode *node0, ObjectType *&rep0, stMIndexNode *node1, ObjectType *&rep1, EvaluatorType *metricEvaluator)
int Distribute (stMLeafNode *node0, ObjectType *&rep0, stMLeafNode *node1, ObjectType *&rep1, EvaluatorType *metricEvaluator)
int TestDistribution (stMIndexNode *node0, stMIndexNode *node1, EvaluatorType *metricEvaluator)
int TestDistribution (stMLeafNode *node0, stMLeafNode *node1, EvaluatorType *metricEvaluator)
void SetMinOccupation (int min)
stNodeType GetNodeType ()
void SetNodeType (stNodeType type)
bool IsRepresentative (int idx)
ObjectType * BuyObject (int idx)
Detailed Description
template<class ObjectType, class EvaluatorType>
class stMLogicNode< ObjectType, EvaluatorType >
Thic class template represents a MTree logic node entry. It is used to hold an index node or a leaf node in a memory form which allows better way to manipulate entries. It also implements means to distribute its contents between 2 nodes.
Each entry of this node can hold all information required by both nodes at same time so, the users of this node must control if it holds an index node or a leaf node.
Warning
This node will take the ownership of all object instances added to this node. It means that the object instance will be destroyed by the destructor of this class.
Version
1.0
Author
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Todo:
Documentation review.
Definition at line 117 of file stMTree.h.
Constructor & Destructor Documentation
template<class ObjectType , class EvaluatorType > stMLogicNode< ObjectType, EvaluatorType >::stMLogicNode (int maxOccupation)
Creates a new instance of this node with no objects.
Parameters
maxOccupation The maximum number of entries.
template<class ObjectType , class EvaluatorType > stMLogicNode< ObjectType, EvaluatorType >::~stMLogicNode ()
Disposes this instance and releases all related resources. All instances of object added to this node will also be deleted unless it is not owned by this node (see method BuyObject()).
Member Function Documentation
template<class ObjectType , class EvaluatorType > int stMLogicNode< ObjectType, EvaluatorType >::AddEntry (ObjectType * obj) inline
Adds an object to this node. This method will claim the ownership of the object instance.
Use SetEntry() to fill the other fields of each entry.
Parameters
obj The object to be added.
Returns
The entry id or -1 for error.
Definition at line 142 of file stMTree.h.
template<class ObjectType , class EvaluatorType > int stMLogicNode< ObjectType, EvaluatorType >::AddEntry (stSize size, const stByte * object)
Adds an object to this node.
Use SetEntry() to fill the other fields of each entry.
Parameters
size The size of the object in bytes.
object The object data.
Returns
The entry id or -1 for error.
template<class ObjectType , class EvaluatorType > void stMLogicNode< ObjectType, EvaluatorType >::AddIndexNode (stMIndexNode * node)
Adds all objects of an index node. It will also set the node type to stMNode::INDEX.
Parameters
node The node.
template<class ObjectType , class EvaluatorType > void stMLogicNode< ObjectType, EvaluatorType >::AddLeafNode (stMLeafNode * node)
Adds all objects of a leaf node. It will also set the node type to stMNode::LEAF.
Parameters
node The node.
template<class ObjectType , class EvaluatorType > ObjectType* stMLogicNode< ObjectType, EvaluatorType >::BuyObject (int idx) inline
Gets the ownership of an object associated with a given entry. This method will avoid the automatic destruction of the object instance by the destructor of this node.
This method can be used to buy the representative objects to avoid unnecessary replications.
Parameters
idx The object index.
Returns
The pointer to the object.
Definition at line 393 of file stMTree.h.
Referenced by stMLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > int stMLogicNode< ObjectType, EvaluatorType >::Distribute (stMIndexNode * node0, ObjectType *& rep0, stMIndexNode * node1, ObjectType *& rep1, EvaluatorType * metricEvaluator) inline
Distribute objects between 2 index nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
rep0 Representative of node 0.
node1 The second node.
rep0 Representative of node 1.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
Definition at line 275 of file stMTree.h.
References stMLogicNode< ObjectType, EvaluatorType >::BuyObject(), stMLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex(), and stMLogicNode< ObjectType, EvaluatorType >::TestDistribution().
template<class ObjectType , class EvaluatorType > int stMLogicNode< ObjectType, EvaluatorType >::Distribute (stMLeafNode * node0, ObjectType *& rep0, stMLeafNode * node1, ObjectType *& rep1, EvaluatorType * metricEvaluator) inline
Distribute objects between 2 leaf nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
rep0 Representative of node 0.
node1 The second node.
rep1 Representative of node 1.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
Definition at line 302 of file stMTree.h.
References stMLogicNode< ObjectType, EvaluatorType >::BuyObject(), stMLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex(), and stMLogicNode< ObjectType, EvaluatorType >::TestDistribution().
template<class ObjectType , class EvaluatorType > stNodeType stMLogicNode< ObjectType, EvaluatorType >::GetNodeType () inline
Returns the node type. It may assume the values stMNode::INDEX or stMNode::LEAF.
Definition at line 361 of file stMTree.h.
template<class ObjectType , class EvaluatorType > int stMLogicNode< ObjectType, EvaluatorType >::GetNumberOfEntries () inline
Returns the number of entries in this node.
Definition at line 164 of file stMTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stMLogicNode< ObjectType, EvaluatorType >::GetObject (int idx) inline
Returns the object of a given entry.
Parameters
idx The object index.
Definition at line 173 of file stMTree.h.
template<class ObjectType , class EvaluatorType > stPageID stMLogicNode< ObjectType, EvaluatorType >::GetPageID (int idx) inline
Returns the PageID of a given entry. Only index nodes will use this field.
Parameters
idx The object index.
Definition at line 191 of file stMTree.h.
template<class ObjectType , class EvaluatorType > stDistance stMLogicNode< ObjectType, EvaluatorType >::GetRadius (int idx) inline
Returns the radius of the sub-tree of a given entry. Only index nodes will use this field.
Parameters
idx The object index.
Definition at line 201 of file stMTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stMLogicNode< ObjectType, EvaluatorType >::GetRepresentative (int idx) inline
Returns the representative object.
Parameters
id The representative ID. It may be 0 or 1.
Definition at line 247 of file stMTree.h.
template<class ObjectType , class EvaluatorType > int stMLogicNode< ObjectType, EvaluatorType >::GetRepresentativeIndex (int idx) inline
Returns the id of the representative object.
Parameters
id The representative ID. It may be 0 or 1.
Definition at line 238 of file stMTree.h.
Referenced by stMLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > bool stMLogicNode< ObjectType, EvaluatorType >::IsRepresentative (int idx) inline
Verifies if a given object is a representative.
Parameters
idx Object index.
Returns
True if the object is a representative or false otherwise.
Definition at line 378 of file stMTree.h.
template<class ObjectType , class EvaluatorType > ObjectType* stMLogicNode< ObjectType, EvaluatorType >::operator[] (int idx) inline
Returns the object of a given entry.
Parameters
idx The object index.
Definition at line 182 of file stMTree.h.
template<class ObjectType , class EvaluatorType > void stMLogicNode< ObjectType, EvaluatorType >::SetEntry (int idx, stPageID pageID, stDistance radius) inline
Sets the data associated with a given entry.
Parameters
idx The object index.
pageID The pageID.
radius The radius of the sub-tree.
Definition at line 212 of file stMTree.h.
template<class ObjectType , class EvaluatorType > void stMLogicNode< ObjectType, EvaluatorType >::SetMinOccupation (int min) inline
Set minimum occupation. This must be the minimum number of objects in a page. This value must be at least 1.
Definition at line 349 of file stMTree.h.
template<class ObjectType , class EvaluatorType > void stMLogicNode< ObjectType, EvaluatorType >::SetNodeType (stNodeType type) inline
Sets the node type.
Definition at line 368 of file stMTree.h.
template<class ObjectType , class EvaluatorType > void stMLogicNode< ObjectType, EvaluatorType >::SetRepresentative (int rep0, int rep1) inline
Sets both representatives ids. Use UpdateDistances() to update all distances between objects and.
Parameters
rep0 Index of representative 0.
rep1 Index of representative 1.
Definition at line 258 of file stMTree.h.
template<class ObjectType , class EvaluatorType > int stMLogicNode< ObjectType, EvaluatorType >::TestDistribution (stMIndexNode * node0, stMIndexNode * node1, EvaluatorType * metricEvaluator)
Tests the distribution of objects between 2 index nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
node1 The second node.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
Warning
Since it is just a test fnction, it will not inialize the fields of the entries.
Referenced by stMLogicNode< ObjectType, EvaluatorType >::Distribute().
template<class ObjectType , class EvaluatorType > int stMLogicNode< ObjectType, EvaluatorType >::TestDistribution (stMLeafNode * node0, stMLeafNode * node1, EvaluatorType * metricEvaluator)
Tests the distribution of objects between 2 leaf nodes using the current representatives (see SetRepresentative()). Both nodes must be empty.
Parameters
node0 The first node.
node1 The second node.
metricEvaluator The metric evaluator to be used to compute distances.
Returns
The number of computed distances.
The documentation for this class was generated from the following file:
stMTree.h
Copyright © 2002-2003 GBDI-ICMC-USP