stMAMViewExtractor< ObjectType, EvaluatorType > Class Template Reference
GBDI Arboretum
Version Release 1
stMAMViewExtractor< ObjectType, EvaluatorType > Class Template Reference
#include <stMAMView.h>
Public Member Functions
stMAMViewExtractor (EvaluatorType *eval)
virtual ~stMAMViewExtractor ()
void Init (stMAMViewObjectSample< ObjectType > *sample)
void BeginAnimation (const char *title=NULL, const char *comment=NULL)
void EndAnimation ()
void BeginFrame (const char *comment)
void EndFrame ()
void SetNode (stPageID nodeID, ObjectType **reps, stDistance *radii, int n, stPageID parent, int type, bool active=false)
void SetNode (stPageID nodeID, ObjectType *rep, stDistance radius, stPageID parent, int type, bool active=false)
void EnableNode (stPageID nodeID)
void SetObject (ObjectType *obj, stPageID parent, bool active=false)
void SetResult (ObjectType *queryObj, stResult< ObjectType > *result, stCount k, stDistance radius)
void SetResult (ObjectType *queryObj, stResult< ObjectType > *result)
void SetSample (ObjectType *queryObj)
void SetQueryInfo (int k, stDistance radius)
void SetLevel (int level)
int GetLevel ()
void LevelUp ()
void LevelDown ()
void SetOutputDir (const char *outputDir)
void SetSerial (int serial)
int GetSerial ()
Detailed Description
template<class ObjectType, class EvaluatorType>
class stMAMViewExtractor< ObjectType, EvaluatorType >
This class template implements the MAM View extractor.
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Todo:
Documentation missing.
Pivot storage support not implemented.
Definition at line 255 of file stMAMView.h.
Constructor & Destructor Documentation
template<class ObjectType , class EvaluatorType > stMAMViewExtractor< ObjectType, EvaluatorType >::stMAMViewExtractor (EvaluatorType * eval) inline
Creates a new instance of this extractor. This instance will not be ready to use until the first call of Init().
Parameters
eval An instance of the metric evaluator. This instance will never be disposed.
Definition at line 264 of file stMAMView.h.
template<class ObjectType , class EvaluatorType > virtual stMAMViewExtractor< ObjectType, EvaluatorType >::~stMAMViewExtractor () virtual
Member Function Documentation
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::BeginAnimation (const char * title = NULL, const char * comment = NULL)
Declares the beginning of an animation. It must be called before any other declaration methods. Both title and comment parameter are optional.
Parameters
title The title of this animation.
comment A little comment text about the animation.
Bug:
Both fields do not support > and < characters.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::BeginFrame (const char * comment)
Declares the beginning of a frame.
Parameters
comment A little comment text about the frame.
Warning
This command is not allowed outside an animation.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::EnableNode (stPageID nodeID)
Changes the state of a node to enabled. The node must exists or the command will not produce any result.
Parameters
nodeID The ID of the node.
Warning
This command is not allowed outside a frame.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::EndAnimation ()
Declares the end of the animation. It must be the last command of an animation.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::EndFrame ()
Declares the end of a frame.
Warning
This command is not allowed outside an animation.
template<class ObjectType , class EvaluatorType > int stMAMViewExtractor< ObjectType, EvaluatorType >::GetLevel () inline
Returns the current level for all declaration commands.
See also
LevelUp()
LevelDown()
SetLevel()
Definition at line 440 of file stMAMView.h.
template<class ObjectType , class EvaluatorType > int stMAMViewExtractor< ObjectType, EvaluatorType >::GetSerial () inline
Gets the serial number of the animation. Useful to save the state of the visualization.
Parameters
serial The first serial number for animations.
Definition at line 490 of file stMAMView.h.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::Init (stMAMViewObjectSample< ObjectType > * sample)
Initializes the mapper to be used by this extractor. It requires a set of objects (at least 50) which must be representative to the whole set of objects.
Parameters
sample A sample of objects.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::LevelDown () inline
Subtracts 1 from current level.
See also
GetLevel()
LevelUp()
SetLevel()
Definition at line 462 of file stMAMView.h.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::LevelUp () inline
Adds 1 to the current level.
See also
GetLevel()
LevelDown()
SetLevel()
Definition at line 451 of file stMAMView.h.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetLevel (int level) inline
Sets the current level for all declaration commands.
Parameters
level Current level.
See also
GetLevel()
LevelUp()
LevelDown()
Definition at line 429 of file stMAMView.h.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetNode (stPageID nodeID, ObjectType ** reps, stDistance * radii, int n, stPageID parent, int type, bool active = false)
Declares a node with multiple representative objects. If the node already exists, it will be overwritten.
Parameters
nodeID The ID of the node. It must be unique for each node.
reps The set of representative objects.
radii The set of radius for each representative.
n The number of representative.
parent The parent node.
type The type ID.
active The declaration state.
Warning
This command is not allowed outside a frame.
Referenced by stMAMViewExtractor< ObjectType, EvaluatorType >::SetNode().
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetNode (stPageID nodeID, ObjectType * rep, stDistance radius, stPageID parent, int type, bool active = false) inline
Declares a node with only one representative object.
Parameters
nodeID The ID of the node. It must be unique for each node.
rep The set of representative objects.
radius The set of radius for each representative.
parent The parent node.
type The type ID.
active The declaration state.
Warning
This command is not allowed outside a frame.
Definition at line 344 of file stMAMView.h.
References stMAMViewExtractor< ObjectType, EvaluatorType >::SetNode().
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetObject (ObjectType * obj, stPageID parent, bool active = false)
Declares an object. The object is identified by its coordinates and its parent. The existing object will be overwritten.
Parameters
obj The object.
parent Its parent.
active The current state.
Warning
This command is not allowed outside a frame.
Bug:
Two objects with the same pair coordinates/parent will be considered the same. A solution to this is on he way.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetOutputDir (const char * outputDir)
Set the output directory. All XML files will be stored in this directory.
Parameters
outputDir The output directory. If none, it will assume the current directory as the output directory.
Referenced by stSlimTree< ObjectType, EvaluatorType >::MAMViewSetOutputDir().
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetQueryInfo (int k, stDistance radius) inline
Sets the default values to k and radius of a query. Useful when both values do not change during an animation. This method is used in combination with SetResult(ObjectType,stResult<ObjectType>) method.
Parameters
k Desired k or 0 if it is not important.
radius Desired radius or 0 if it is not important.
Definition at line 416 of file stMAMView.h.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetResult (ObjectType * queryObj, stResult< ObjectType > * result, stCount k, stDistance radius)
Declares the result state.
Parameters
queryObj The query object.
result Current result state.
k Desired k or 0 if it is not important.
radius Desired radius or 0 if it is not important.
See also
SetResult(ObjectType,stResult<ObjectType>)
Warning
This command is not allowed outside a frame.
Referenced by stMAMViewExtractor< ObjectType, EvaluatorType >::SetResult().
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetResult (ObjectType * queryObj, stResult< ObjectType > * result) inline
Declares the result state using the default k and radius values. See SetQueryInfo() for more details.
Parameters
queryObj The query object.
result Current result state.
See also
SetResult(ObjectType,stResult<ObjectType>,stCount,stDistance)
SetQueryInfo()
Warning
This command is not allowed outside a frame.
Definition at line 394 of file stMAMView.h.
References stMAMViewExtractor< ObjectType, EvaluatorType >::SetResult().
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetSample (ObjectType * queryObj) inline
Declares a result with only the sample object. It may be used to declare the input object of an add operation.
Parameters
queryObj The query object.
Warning
This command is not allowed outside a frame.
Todo:
This method is not implemented yet.
Definition at line 406 of file stMAMView.h.
template<class ObjectType , class EvaluatorType > void stMAMViewExtractor< ObjectType, EvaluatorType >::SetSerial (int serial) inline
Sets the serial number of the animation. By default it starts with 0.
Parameters
serial The first serial number for animations.
Definition at line 480 of file stMAMView.h.
The documentation for this class was generated from the following file:
stMAMView.h
Copyright © 2002-2003 GBDI-ICMC-USP