stClientPageManager Class Reference
GBDI Arboretum
Version Release 1
stClientPageManager Class Reference
#include <stClientPageManager.h>
Public Member Functions
stClientPageManager (int clientID, stPageServer *server)
virtual bool IsEmpty ()
virtual stPage * GetHeaderPage ()
virtual stPage * GetPage (stPageID pageid)
virtual void ReleasePage (stPage *page)
virtual stPage * GetNewPage ()
virtual void WritePage (stPage *page)
virtual void DisposePage (stPage *page)
virtual stSize GetMinimumPageSize ()
int GetClientID ()
stPageServer * GetServer ()
Public Member Functions inherited from stPageManager
virtual ~stPageManager ()
virtual void WriteHeaderPage (stPage *headerpage)
virtual void ResetStatistics ()
long int GetReadCount ()
long int GetWriteCount ()
long int GetAccessCount ()
Additional Inherited Members
Protected Member Functions inherited from stPageManager
void UpdateReadCounter (unsigned long count=1)
void UpdateWriteCounter (unsigned long count=1)
Detailed Description
This class defines the class stClientPageManager. It uses a page server to provide access to a block device.
Version
1.0
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
See also
stPageServer
Todo:
Tests!
Definition at line 92 of file stClientPageManager.h.
Constructor & Destructor Documentation
stClientPageManager::stClientPageManager (int clientID, stPageServer * server) inline
Creates a new instance of a client page manager. Do not call this constructor if you are not a page server creator.
Parameters
clientID Client ID.
server The server to be used.
Definition at line 101 of file stClientPageManager.h.
Member Function Documentation
virtual void stClientPageManager::DisposePage (stPage * page) inline virtual
Disposes the given page. This method will make the page available (not allocated) for the next calls of GetNewPage().
Since this page will not be used anymore, this method will release the lock for this page instance.
Parameters
page The page to be disposed.
See also
GetNewPage()
Implements stPageManager.
Definition at line 214 of file stClientPageManager.h.
References stPageServer::DisposePage().
int stClientPageManager::GetClientID () inline
Returns the client ID.
Definition at line 229 of file stClientPageManager.h.
virtual stPage* stClientPageManager::GetHeaderPage () inline virtual
Returns the header page. This method will return a special page that will be used by SlimTree to write some information about the tree itself.
Since this page must always exist, this method will always return a valid page for reading/writing. Use WritePage() to write this page.
The returning instance of stPage will be locked to prevent its reuse by this page manager. Use ReleasePage() to unlock this instance.
Returns
The header page.
See also
WritePage()
ReleasePage()
Implements stPageManager.
Definition at line 134 of file stClientPageManager.h.
References GetPage().
virtual stSize stClientPageManager::GetMinimumPageSize () inline virtual
Returns the minimum size of a page. The size of the header page is always ignored since it may be smaller than others.
Implements stPageManager.
Definition at line 222 of file stClientPageManager.h.
References stPageServer::GetPageSize().
virtual stPage* stClientPageManager::GetNewPage () inline virtual
Allocates a new page for use. As GetPage() and GetHeaderPage(), the returning instance will be locked to prevent reuse by this page manager.
To dispose this page (make it free), use DisposePage().
Returns
A new page or NULL for errors.
See also
ReleasePage()
WritePage()
DisposePage()
Implements stPageManager.
Definition at line 187 of file stClientPageManager.h.
References stPageServer::GetNewPage().
virtual stPage* stClientPageManager::GetPage (stPageID pageid) inline virtual
Returns the page with the given page ID. This method will return a valid page for reading/writing. Use WritePage() to write this page.
The returning instance of stPage will be locked to prevent its reuse by this page manager. Use ReleasePage() to unlock this instance.
Parameters
pageid The desired page id.
Returns
The page or NULL for an invalid page ID.
See also
WritePage()
ReleasePage()
Implements stPageManager.
Definition at line 152 of file stClientPageManager.h.
References stPageServer::GetPage(), and stPageManager::UpdateReadCounter().
Referenced by GetHeaderPage().
stPageServer* stClientPageManager::GetServer () inline
Returns the server used by this client.
Definition at line 236 of file stClientPageManager.h.
virtual bool stClientPageManager::IsEmpty () inline virtual
This method will checks if this page manager is empty. If this method returns true, the stSlimTree will create a new tree otherwise it will continue to use the existing tree.
Returns
True if the page manager is empty or false otherwise.
Implements stPageManager.
Definition at line 113 of file stClientPageManager.h.
References stPageServer::GetPageCount().
virtual void stClientPageManager::ReleasePage (stPage * page) inline virtual
Releases this instace for reuse by this page manager. Since some implementations of page manager will reuse instances of stPage to avoid unnecessary resource reallocations, each page instance must be locked until it becomes unecessary.
The stSlimTree will always call this method when a stPage instance will not be used in a near future.
Parameters
page The locked page.
See also
GetPage()
GetHeaderPage()
Implements stPageManager.
Definition at line 171 of file stClientPageManager.h.
References stPageServer::ReleasePage().
virtual void stClientPageManager::WritePage (stPage * page) inline virtual
Writes the given page to the disk. This method will write the page but will not release it. Use ReleasePage() to do it.
Parameters
page The page to be written.
See also
ReleasePage()
WriteHeaderPage()
Implements stPageManager.
Definition at line 200 of file stClientPageManager.h.
References stPageServer::WritePage().
The documentation for this class was generated from the following file:
stClientPageManager.h
Copyright © 2002-2003 GBDI-ICMC-USP