stMNode Class Reference
GBDI Arboretum
Version Release 1
stMNode Class Reference abstract
#include <stMNode.h>
Classes
struct stMNodeHeader
Public Types
enum stMNodeType { INDEX = 0x4449, LEAF = 0x464C }
Public Member Functions
virtual ~stMNode ()
stNodeType GetNodeType ()
stPage * GetPage ()
stPageID GetPageID ()
int GetNumberOfEntries ()
virtual int AddEntry (stSize size, const stByte *object)=0
virtual const stByte * GetObject (int id)=0
virtual stSize GetObjectSize (int id)=0
virtual stDistance GetMinimumRadius ()=0
void RemoveAll ()
Static Public Member Functions
static stMNode * CreateNode (stPage *page)
static stSize GetGlobalOverhead ()
Protected Types
typedef struct stMNode::stMNodeHeader stMNodeHeader
Protected Member Functions
stMNode (stPage *page)
Protected Attributes
stMNodeHeader * Header
stPage * Page
Detailed Description
This abstract class is the basic MTree node. All classes that implement MTree nodes must extend this class.
The main function of this class is to provide a way to identify a disk node and create the required node instance to manipulate the node.
The structure of Index Node follows:
M node structure
The Header holds the information about the node itself.
Type: Type of this node. It may be stMNode::INDEX or stMNode::LEAF.
Occupation: Number of entries in this node.
The Node Data is the segment of the node which holds the particular information of each type of the node. This class does not know how this information is organized.
Author
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Version
1.0
Todo:
Documentation review.
See also
stMIndexNode
stMLeafNode
Definition at line 108 of file stMNode.h.
Member Typedef Documentation
typedef struct stMNode::stMNodeHeader stMNode::stMNodeHeader protected
This is the structure of the Header of a MTree node.
Member Enumeration Documentation
enum stMNode::stMNodeType
Node type.
Enumerator
INDEX
ID of an index node.
LEAF
ID of a leaf node.
Definition at line 113 of file stMNode.h.
Constructor & Destructor Documentation
virtual stMNode::~stMNode () inline virtual
This method will dispose this instance and all associated resources.
Definition at line 128 of file stMNode.h.
stMNode::stMNode (stPage * page) inline protected
Creates a new instance of this class.
Parameters
page An instance of stPage.
Definition at line 276 of file stMNode.h.
References stPage::GetData().
Member Function Documentation
virtual int stMNode::AddEntry (stSize size, const stByte * object) pure virtual
This is a virtual method that defines a interface in the insertion of a new Object in a Node.
Parameters
size The size of the object in bytes.
object The object data.
Warning
The parameter size is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The position in the vector Entries.
See also
RemoveObject()
Implemented in stMLeafNode, and stMIndexNode.
static stMNode* stMNode::CreateNode (stPage * page) static
This is a virtual method that defines a interface for the instantiate the correct specialization of this class.
Parameters
page The instance of stPage.
static stSize stMNode::GetGlobalOverhead () inline static
Returns the global overhead of a slim node (header size) in bytes.
Definition at line 239 of file stMNode.h.
virtual stDistance stMNode::GetMinimumRadius () pure virtual
Returns the minimum radius of this node.
Implemented in stMLeafNode, and stMIndexNode.
stNodeType stMNode::GetNodeType () inline
Returns the type of this MTree node (Leaf or Index).
Returns
the type of node.
See also
stNodeType
Definition at line 137 of file stMNode.h.
References Header, and stMNode::stMNodeHeader::Type.
int stMNode::GetNumberOfEntries () inline
Returns the number of entries in this node.
Returns
the number of entries.
See also
GetEntry()
GetObject()
GetObjectSize()
Definition at line 175 of file stMNode.h.
References Header, and stMNode::stMNodeHeader::Occupation.
Referenced by stMIndexNode::GetIndexEntry(), and stMLeafNode::GetLeafEntry().
virtual const stByte* stMNode::GetObject (int id) pure virtual
Gets the serialized object. Use GetObjectSize to determine the size of the object.
Parameters
id The id of the entry.
Warning
The parameter id is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
A pointer to the serialized object.
See also
GetObjectSize()
Implemented in stMLeafNode, and stMIndexNode.
virtual stSize stMNode::GetObjectSize (int id) pure virtual
Returns the size of the object in bytes. Use GetObject() to get the object data.
Parameters
id The id of the entry.
Warning
The parameter id is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The size of the serialized object.
See also
GetObject()
Implemented in stMLeafNode, and stMIndexNode.
stPage* stMNode::GetPage () inline
Returns the associated page.
Returns
The associated page.
Definition at line 146 of file stMNode.h.
References Page.
stPageID stMNode::GetPageID () inline
Returns the ID of the associated page.
Returns
The ID of the associated page.
Definition at line 155 of file stMNode.h.
References stPage::GetPageID(), and Page.
void stMNode::RemoveAll () inline
Remove All entries.
Definition at line 224 of file stMNode.h.
References stPage::Clear(), Header, stMNode::stMNodeHeader::Occupation, Page, and stMNode::stMNodeHeader::Type.
Member Data Documentation
stMNodeHeader* stMNode::Header protected
Header of this page.
Definition at line 264 of file stMNode.h.
Referenced by GetNodeType(), GetNumberOfEntries(), and RemoveAll().
stPage* stMNode::Page protected
The page related with this class.
Definition at line 269 of file stMNode.h.
Referenced by GetPage(), GetPageID(), and RemoveAll().
The documentation for this class was generated from the following file:
stMNode.h
Copyright © 2002-2003 GBDI-ICMC-USP