stSlimLeafNode Class Reference
GBDI Arboretum
Version Release 1
stSlimLeafNode Class Reference
#include <stSlimNode.h>
Classes
struct stSlimLeafEntry
Public Types
typedef struct stSlimLeafNode::stSlimLeafEntry stSlimLeafEntry
Public Types inherited from stSlimNode
enum stSlimNodeType { INDEX = 0x4449, LEAF = 0x464C }
Public Member Functions
stSlimLeafNode (stPage *page, bool create=false)
stSlimLeafEntry & GetLeafEntry (stCount idx)
virtual int AddEntry (stSize size, const stByte *object)
int GetRepresentativeEntry ()
const stByte * GetObject (stCount idx)
stSize GetObjectSize (stCount idx)
void RemoveEntry (stCount idx)
virtual stDistance GetMinimumRadius ()
virtual stCount GetTotalObjectCount ()
Public Member Functions inherited from stSlimNode
virtual ~stSlimNode ()
stNodeType GetNodeType ()
stPage * GetPage ()
stPageID GetPageID ()
stCount GetNumberOfEntries ()
void RemoveAll ()
Static Public Member Functions
static stSize GetLeafEntryOverhead ()
Static Public Member Functions inherited from stSlimNode
static stSlimNode * CreateNode (stPage *page)
static stSize GetGlobalOverhead ()
Additional Inherited Members
Protected Types inherited from stSlimNode
typedef struct stSlimNode::stSlimNodeHeader stSlimNodeHeader
Protected Member Functions inherited from stSlimNode
stSlimNode (stPage *page)
Protected Attributes inherited from stSlimNode
stSlimNodeHeader * Header
stPage * Page
Detailed Description
This class implements the Leaf node of the SlimTree.
The SlimTree leaf node... The structure of Leaf Node follows:
Leaf node structure
The Header holds the information about the node itself.
Type: Type of this node. It is always stSlimNode::LEAF (0x464C).
Occupation: Number of entries in this node.
The Entry holds the information of the link to the other node.
Distance: The distance of this object from the representative object.
Offset: The offset of the object in the page. DO NOT MODIFY ITS VALUE.
The Object is an array of bytes that holds the information required to rebuild the original object.
Version
1.0
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Josiel Maimone de Figueiredo (josie.nosp@m.l@ic.nosp@m.mc.us.nosp@m.p.br)
Todo:
Documentation review.
See also
stSlimNode
stSlimIndexNode
stSlimMemLeafNode
Definition at line 523 of file stSlimNode.h.
Member Typedef Documentation
typedef struct stSlimLeafNode::stSlimLeafEntry stSlimLeafNode::stSlimLeafEntry
This type represents a slim tree leaf node entry.
Constructor & Destructor Documentation
stSlimLeafNode::stSlimLeafNode (stPage * page, bool create = false)
Creates a new instance of this class. The paramenter page is an instance of stPage that hold the node data.
The parameter create tells to stLeafPage what operation will be performed. True means that the page will be initialized and false means that the page will be used as it is. The default value is false.
Parameters
page The page that hold the data of this node.
create The operation to be performed.
Member Function Documentation
virtual int stSlimLeafNode::AddEntry (stSize size, const stByte * object) virtual
Adds a new entry to this node. This method will return the idx of the new node or a negative value for failure.
This method will fail if there is not enough space to hold the new object.
If you have added a new entry successfully, you may edit the entry fields using the method GetEntry().
Parameters
size The size of the object in bytes.
object The object data.
Warning
The parameter size is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The position in the vector Entries.
See also
RemoveEntry()
GetEntry()
Implements stSlimNode.
stSlimLeafEntry& stSlimLeafNode::GetLeafEntry (stCount idx) inline
Returns the reference of the desired leaf entry. You may use this method to read and modify the leaf entry information.
Parameters
idx The idx of the leaf entry.
Warning
The parameter idx is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
stLeafEntry the reference of the desired entry.
See also
stLeafEntry
GetNumberOfEntries()
GetObject()
GetObjectSize()
Definition at line 570 of file stSlimNode.h.
References stSlimNode::GetNumberOfEntries().
static stSize stSlimLeafNode::GetLeafEntryOverhead () inline static
Returns the overhead of each leaf node entry in bytes.
Definition at line 657 of file stSlimNode.h.
Referenced by stSlimMemLeafNode< ObjectType >::CanAdd().
virtual stDistance stSlimLeafNode::GetMinimumRadius () virtual
Returns the minimum radius of this node.
Implements stSlimNode.
const stByte* stSlimLeafNode::GetObject (stCount idx) virtual
Gets the serialized object. Use GetObjectSize() to determine the size of the object.
Parameters
idx The idx of the entry.
Warning
The parameter idx is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
A pointer to the serialized object.
See also
GetObjectSize()
Implements stSlimNode.
stSize stSlimLeafNode::GetObjectSize (stCount idx) virtual
Returns the size of the object. Use GetObject() to get the object data.
Parameters
idx The idx of the entry.
Warning
The parameter idx is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The size of the serialized object.
See also
GetObject()
Implements stSlimNode.
int stSlimLeafNode::GetRepresentativeEntry ()
Returns the entry idx that hold the representative object.
Returns
-1 if there is not a representative in the current node. Otherwise there is.
virtual stCount stSlimLeafNode::GetTotalObjectCount () inline virtual
Returns the total number of objects in the subtree.
Implements stSlimNode.
Definition at line 650 of file stSlimNode.h.
References stSlimNode::GetNumberOfEntries().
void stSlimLeafNode::RemoveEntry (stCount idx)
Removes an entry from this object.
Parameters
idx The idx of the entry.
Warning
The parameter idx is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
A pointer to the serialized object.
See also
GetObjectSize()
Todo:
This method is not implemented yet.
The documentation for this class was generated from the following file:
stSlimNode.h
Copyright © 2002-2003 GBDI-ICMC-USP