stDFNode Class Reference
GBDI Arboretum
Version Release 1
stDFNode Class Reference abstract
#include <stDFNode.h>
Classes
struct stDFNodeHeader
Public Types
enum stDFNodeType { INDEX = 0x4449, LEAF = 0x464C }
Public Member Functions
virtual ~stDFNode ()
stNodeType GetNodeType ()
stPage * GetPage ()
stPageID GetPageID ()
stCount GetNumberOfEntries ()
virtual int AddEntry (stSize size, const stByte *object)=0
virtual const stByte * GetObject (stCount idx)=0
virtual stSize GetObjectSize (stCount idx)=0
virtual stDistance GetMinimumRadius ()=0
void RemoveAll ()
virtual stCount GetTotalObjectCount ()=0
Static Public Member Functions
static stDFNode * CreateNode (stPage *page)
static stSize GetGlobalOverhead ()
Protected Types
typedef struct stDFNode::stDFNodeHeader stDFNodeHeader
Protected Member Functions
stDFNode (stPage *page)
Protected Attributes
stDFNodeHeader * Header
stPage * Page
Detailed Description
This abstract class is the basic DFTree node. All classes that implement DFTree nodes must extend this class.
The main function of this class is to provide a way to identify a disk node and create the required node instance to manipulate the node.
The structure of Index Node follows:
DF node structure
The Header holds the information about the node itself.
Type: Type of this node. It may be stDFNode::INDEX or stDFNode::LEAF.
Occupation: Number of entries in this node.
The Node Data is the segment of the node which holds the particular information of each type of the node. This class does not know how this information is organized.
Author
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Version
1.0
Todo:
Documentation review.
See also
stDFIndexNode
stDFLeafNode
Definition at line 112 of file stDFNode.h.
Member Typedef Documentation
typedef struct stDFNode::stDFNodeHeader stDFNode::stDFNodeHeader protected
This is the structure of the Header of a DFTree node.
Member Enumeration Documentation
enum stDFNode::stDFNodeType
Node type.
Enumerator
INDEX
ID of an index node.
LEAF
ID of a leaf node.
Definition at line 119 of file stDFNode.h.
Constructor & Destructor Documentation
virtual stDFNode::~stDFNode () inline virtual
This method will dispose this instance and all associated resources.
Definition at line 134 of file stDFNode.h.
stDFNode::stDFNode (stPage * page) inline protected
Creates a new instance of this class.
Parameters
page An instance of stPage.
Definition at line 287 of file stDFNode.h.
References stPage::GetData().
Member Function Documentation
virtual int stDFNode::AddEntry (stSize size, const stByte * object) pure virtual
This is a virtual method that defines a interface in the insertion of a new Object in a Node.
Parameters
size The size of the object in bytes.
object The object data.
Warning
The parameter size is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The position in the vector Entries.
See also
RemoveObject()
Implemented in stDFLeafNode, and stDFIndexNode.
static stDFNode* stDFNode::CreateNode (stPage * page) static
This is a virtual method that defines a interface for the instantiate the correct specialization of this class.
Parameters
page The instance of stPage.
static stSize stDFNode::GetGlobalOverhead () inline static
Returns the global overhead of a DF node (header size) in bytes.
Definition at line 250 of file stDFNode.h.
virtual stDistance stDFNode::GetMinimumRadius () pure virtual
Returns the minimum radius of this node.
Implemented in stDFLeafNode, and stDFIndexNode.
stNodeType stDFNode::GetNodeType () inline
Returns the type of this DFTree node (Leaf or Index).
Returns
the type of node.
See also
stNodeType
Definition at line 143 of file stDFNode.h.
References Header, and stDFNode::stDFNodeHeader::Type.
stCount stDFNode::GetNumberOfEntries () inline
Returns the number of entries in this node.
Returns
the number of entries.
See also
GetEntry()
GetObject()
GetObjectSize()
Definition at line 181 of file stDFNode.h.
References Header, and stDFNode::stDFNodeHeader::Occupation.
Referenced by stDFIndexNode::GetIndexEntry(), stDFLeafNode::GetLeafEntry(), and stDFLeafNode::GetTotalObjectCount().
virtual const stByte* stDFNode::GetObject (stCount idx) pure virtual
Gets the serialized object. Use GetObjectSize to determine the size of the object.
Parameters
id The id of the entry.
Warning
The parameter id is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
A pointer to the serialized object.
See also
GetObjectSize()
Implemented in stDFLeafNode, and stDFIndexNode.
virtual stSize stDFNode::GetObjectSize (stCount idx) pure virtual
Returns the size of the object in bytes. Use GetObject() to get the object data.
Parameters
id The id of the entry.
Warning
The parameter id is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The size of the serialized object.
See also
GetObject()
Implemented in stDFLeafNode, and stDFIndexNode.
stPage* stDFNode::GetPage () inline
Returns the associated page.
Returns
The associated page.
Definition at line 152 of file stDFNode.h.
References Page.
stPageID stDFNode::GetPageID () inline
Returns the ID of the associated page.
Returns
The ID of the associated page.
Definition at line 161 of file stDFNode.h.
References stPage::GetPageID(), and Page.
virtual stCount stDFNode::GetTotalObjectCount () pure virtual
Returns the total number of objects in the subtree.
Implemented in stDFLeafNode, and stDFIndexNode.
void stDFNode::RemoveAll () inline
Remove All entries.
Definition at line 230 of file stDFNode.h.
References stPage::Clear(), Header, stDFNode::stDFNodeHeader::Occupation, Page, and stDFNode::stDFNodeHeader::Type.
Member Data Documentation
stDFNodeHeader* stDFNode::Header protected
Header of this page.
Definition at line 275 of file stDFNode.h.
Referenced by GetNodeType(), GetNumberOfEntries(), and RemoveAll().
stPage* stDFNode::Page protected
The page related with this class.
Definition at line 280 of file stDFNode.h.
Referenced by GetPage(), GetPageID(), and RemoveAll().
The documentation for this class was generated from the following file:
stDFNode.h
Copyright © 2002-2003 GBDI-ICMC-USP