stSlimNode Class Reference
GBDI Arboretum
Version Release 1
stSlimNode Class Reference abstract
#include <stSlimNode.h>
Classes
struct stSlimNodeHeader
Public Types
enum stSlimNodeType { INDEX = 0x4449, LEAF = 0x464C }
Public Member Functions
virtual ~stSlimNode ()
stNodeType GetNodeType ()
stPage * GetPage ()
stPageID GetPageID ()
stCount GetNumberOfEntries ()
virtual int AddEntry (stSize size, const stByte *object)=0
virtual const stByte * GetObject (stCount idx)=0
virtual stSize GetObjectSize (stCount idx)=0
virtual stDistance GetMinimumRadius ()=0
void RemoveAll ()
virtual stCount GetTotalObjectCount ()=0
Static Public Member Functions
static stSlimNode * CreateNode (stPage *page)
static stSize GetGlobalOverhead ()
Protected Types
typedef struct stSlimNode::stSlimNodeHeader stSlimNodeHeader
Protected Member Functions
stSlimNode (stPage *page)
Protected Attributes
stSlimNodeHeader * Header
stPage * Page
Detailed Description
This abstract class is the basic SlimTree node. All classes that implement SlimTree nodes must extend this class.
The main function of this class is to provide a way to identify a disk node and create the required node instance to manipulate the node.
The structure of Index Node follows:
Slim node structure
The Header holds the information about the node itself.
Type: Type of this node. It may be stSlimNode::INDEX or stSlimNode::LEAF.
Occupation: Number of entries in this node.
The Node Data is the segment of the node which holds the particular information of each type of the node. This class does not know how this information is organized.
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Josiel Maimone de Figueiredo (josie.nosp@m.l@ic.nosp@m.mc.us.nosp@m.p.br)
Version
1.0
Todo:
Documentation review.
See also
stSlimIndexNode
stSlimLeafNode
Definition at line 113 of file stSlimNode.h.
Member Typedef Documentation
typedef struct stSlimNode::stSlimNodeHeader stSlimNode::stSlimNodeHeader protected
This is the structure of the Header of a SlimTree node.
Member Enumeration Documentation
enum stSlimNode::stSlimNodeType
Node type.
Enumerator
INDEX
ID of an index node.
LEAF
ID of a leaf node.
Definition at line 118 of file stSlimNode.h.
Constructor & Destructor Documentation
virtual stSlimNode::~stSlimNode () inline virtual
This method will dispose this instance and all associated resources.
Definition at line 133 of file stSlimNode.h.
stSlimNode::stSlimNode (stPage * page) inline protected
Creates a new instance of this class.
Parameters
page An instance of stPage.
Definition at line 286 of file stSlimNode.h.
References stPage::GetData().
Member Function Documentation
virtual int stSlimNode::AddEntry (stSize size, const stByte * object) pure virtual
This is a virtual method that defines a interface in the insertion of a new Object in a Node.
Parameters
size The size of the object in bytes.
object The object data.
Warning
The parameter size is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The position in the vector Entries.
See also
RemoveObject()
Implemented in stSlimLeafNode, and stSlimIndexNode.
static stSlimNode* stSlimNode::CreateNode (stPage * page) static
This is a virtual method that defines a interface for the instantiate the correct specialization of this class.
Parameters
page The instance of stPage.
static stSize stSlimNode::GetGlobalOverhead () inline static
Returns the global overhead of a slim node (header size) in bytes.
Definition at line 249 of file stSlimNode.h.
virtual stDistance stSlimNode::GetMinimumRadius () pure virtual
Returns the minimum radius of this node.
Implemented in stSlimLeafNode, and stSlimIndexNode.
stNodeType stSlimNode::GetNodeType () inline
Returns the type of this SlimTree node (Leaf or Index).
Returns
the type of node.
See also
stNodeType
Definition at line 142 of file stSlimNode.h.
References Header, and stSlimNode::stSlimNodeHeader::Type.
stCount stSlimNode::GetNumberOfEntries () inline
Returns the number of entries in this node.
Returns
the number of entries.
See also
GetEntry()
GetObject()
GetObjectSize()
Definition at line 180 of file stSlimNode.h.
References Header, and stSlimNode::stSlimNodeHeader::Occupation.
Referenced by stSlimIndexNode::GetIndexEntry(), stSlimLeafNode::GetLeafEntry(), and stSlimLeafNode::GetTotalObjectCount().
virtual const stByte* stSlimNode::GetObject (stCount idx) pure virtual
Gets the serialized object. Use GetObjectSize to determine the size of the object.
Parameters
idx The idx of the entry.
Warning
The parameter idx is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
A pointer to the serialized object.
See also
GetObjectSize()
Implemented in stSlimLeafNode, and stSlimIndexNode.
virtual stSize stSlimNode::GetObjectSize (stCount idx) pure virtual
Returns the size of the object in bytes. Use GetObject() to get the object data.
Parameters
idx The idx of the entry.
Warning
The parameter idx is not verified by this implementation unless stDEBUG is defined at compile time.
Returns
The size of the serialized object.
See also
GetObject()
Implemented in stSlimLeafNode, and stSlimIndexNode.
stPage* stSlimNode::GetPage () inline
Returns the associated page.
Returns
The associated page.
Definition at line 151 of file stSlimNode.h.
References Page.
stPageID stSlimNode::GetPageID () inline
Returns the ID of the associated page.
Returns
The ID of the associated page.
Definition at line 160 of file stSlimNode.h.
References stPage::GetPageID(), and Page.
virtual stCount stSlimNode::GetTotalObjectCount () pure virtual
Returns the total number of objects in the subtree.
Implemented in stSlimLeafNode, and stSlimIndexNode.
void stSlimNode::RemoveAll () inline
Remove All entries.
Definition at line 229 of file stSlimNode.h.
References stPage::Clear(), Header, stSlimNode::stSlimNodeHeader::Occupation, Page, and stSlimNode::stSlimNodeHeader::Type.
Member Data Documentation
stSlimNodeHeader* stSlimNode::Header protected
Header of this page.
Definition at line 274 of file stSlimNode.h.
Referenced by GetNodeType(), GetNumberOfEntries(), and RemoveAll().
stPage* stSlimNode::Page protected
The page related with this class.
Definition at line 279 of file stSlimNode.h.
Referenced by GetPage(), GetPageID(), and RemoveAll().
The documentation for this class was generated from the following file:
stSlimNode.h
Copyright © 2002-2003 GBDI-ICMC-USP