stFastMapImage< ObjectType > Class Template Reference
GBDI Arboretum
Version Release 1
stFastMapImage< ObjectType > Class Template Reference
#include <stFastMapper.h>
Public Member Functions
stFastMapImage (ObjectType *object, int dim, bool ownership=false)
virtual ~stFastMapImage ()
const ObjectType * GetObject ()
void SetObject (ObjectType *obj, bool ownership=false)
double & operator[] (int idx)
void GetCoords (double *coords)
const double * GetCoords ()
void SetCoords (const double *coords)
void SetCoordsTo (double value=0)
int GetDimension ()
stFastMapImage * Clone ()
Detailed Description
template<class ObjectType>
class stFastMapImage< ObjectType >
This class template is a utility class for stFastMapper which can hold an object image (the projected coordinates and a reference to the original object). It is used during the pivot election and to hold the pivot information inside an instance of stFastMapper.
The object type (ObjectType) must implement at least a method named Clone() which can create a perfect clone of the object.
This class template is a companion of stFastMapper and is not supposed to be used by other classes.
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Version
1.0
Warning
This class template used by stFastMapper and should not be used by other classes.
Definition at line 127 of file stFastMapper.h.
Constructor & Destructor Documentation
template<class ObjectType> stFastMapImage< ObjectType >::stFastMapImage (ObjectType * object, int dim, bool ownership = false) inline
Creates a new instance of this class.
Parameters
object The associated object.
dim The number of dimensions.
ownership A flag which tells this image to take ownership of the given object.
Definition at line 137 of file stFastMapper.h.
Referenced by stFastMapImage< ObjectType >::Clone().
template<class ObjectType> virtual stFastMapImage< ObjectType >::~stFastMapImage () inline virtual
Disposes this instance. The object associated with this image will be deleted if this instance owns it.
Definition at line 150 of file stFastMapper.h.
Member Function Documentation
template<class ObjectType> stFastMapImage* stFastMapImage< ObjectType >::Clone () inline
This method creates a perfect clone of this object.
Definition at line 236 of file stFastMapper.h.
References stFastMapImage< ObjectType >::SetCoords(), and stFastMapImage< ObjectType >::stFastMapImage().
template<class ObjectType> void stFastMapImage< ObjectType >::GetCoords (double * coords) inline
Returns all coordinates. The output vector must have at least dim positions.
Return values
coords The output vector.
Definition at line 198 of file stFastMapper.h.
template<class ObjectType> const double* stFastMapImage< ObjectType >::GetCoords () inline
Returns all coordinates in a vector. Do NOT modify these values using this method.
Definition at line 206 of file stFastMapper.h.
template<class ObjectType> int stFastMapImage< ObjectType >::GetDimension () inline
Returns the number of dimensions of this image.
Definition at line 229 of file stFastMapper.h.
template<class ObjectType> const ObjectType* stFastMapImage< ObjectType >::GetObject () inline
Returns the object associated with this instance.
Definition at line 164 of file stFastMapper.h.
template<class ObjectType> double& stFastMapImage< ObjectType >::operator[] (int idx) inline
This operator allows the direct access to each image coordinate.
Definition at line 188 of file stFastMapper.h.
template<class ObjectType> void stFastMapImage< ObjectType >::SetCoords (const double * coords) inline
Sets all coordinates of this image using the input vector of values.
Parameters
coords The input vector.
Definition at line 215 of file stFastMapper.h.
Referenced by stFastMapImage< ObjectType >::Clone().
template<class ObjectType> void stFastMapImage< ObjectType >::SetCoordsTo (double value = 0)
Sets all coordinates to a given value.
Parameters
value A value which will be used to initialize all coordinates.
template<class ObjectType> void stFastMapImage< ObjectType >::SetObject (ObjectType * obj, bool ownership = false) inline
Changes the object. Used for recycle purposes.
Parameters
obj The new object.
ownership A flag which tells this image to take ownership of the given object.
Definition at line 175 of file stFastMapper.h.
The documentation for this class was generated from the following file:
stFastMapper.h
Copyright © 2002-2003 GBDI-ICMC-USP