stPageManager Class Reference
GBDI Arboretum
Version Release 1
stPageManager Class Reference abstract
#include <stPageManager.h>
Public Member Functions
virtual ~stPageManager ()
virtual bool IsEmpty ()=0
virtual void WriteHeaderPage (stPage *headerpage)
virtual stPage * GetHeaderPage ()=0
virtual stPage * GetPage (stPageID pageid)=0
virtual void ReleasePage (stPage *page)=0
virtual stPage * GetNewPage ()=0
virtual void WritePage (stPage *page)=0
virtual void DisposePage (stPage *page)=0
virtual void ResetStatistics ()
long int GetReadCount ()
long int GetWriteCount ()
long int GetAccessCount ()
virtual stSize GetMinimumPageSize ()=0
Protected Member Functions
void UpdateReadCounter (unsigned long count=1)
void UpdateWriteCounter (unsigned long count=1)
Detailed Description
This class defines the abstract class stPageManager. All classes that provide page management service to the SlimTree must extend this class.
Version
1.0
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
See also
stDiskPageManager
stMemoryPageManager
CStorage
Definition at line 93 of file stPageManager.h.
Constructor & Destructor Documentation
virtual stPageManager::~stPageManager () inline virtual
This is de default destructor of this class.
Definition at line 100 of file stPageManager.h.
Member Function Documentation
virtual void stPageManager::DisposePage (stPage * page) pure virtual
Disposes the given page. This method will make the page available (not allocated) for the next calls of GetNewPage().
Since this page will not be used anymore, this method will release the lock for this page instance.
Parameters
page The page to be disposed.
See also
GetNewPage()
Implemented in stDiskPageManager, stPlainDiskPageManager, stMemoryPageManager, and stClientPageManager.
long int stPageManager::GetAccessCount () inline
Returns the total page access. This value is the sum of the read count and write count.
Definition at line 255 of file stPageManager.h.
virtual stPage* stPageManager::GetHeaderPage () pure virtual
Returns the header page. This method will return a special page that will be used by SlimTree to write some information about the tree itself.
Since this page must always exist, this method will always return a valid page for reading/writing. Use WritePage() to write this page.
The returning instance of stPage will be locked to prevent its reuse by this page manager. Use ReleasePage() to unlock this instance.
Returns
The header page.
See also
WritePage()
ReleasePage()
Implemented in stDiskPageManager, stPlainDiskPageManager, stMemoryPageManager, and stClientPageManager.
virtual stSize stPageManager::GetMinimumPageSize () pure virtual
Returns the minimum size of a page. The size of the header page is always ignored since it may be smaller than others.
Implemented in stDiskPageManager, stPlainDiskPageManager, stMemoryPageManager, and stClientPageManager.
virtual stPage* stPageManager::GetNewPage () pure virtual
Allocates a new page for use. As GetPage() and GetHeaderPage(), the returning instance will be locked to prevent reuse by this page manager.
To dispose this page (make it free), use DisposePage().
Returns
A new page or NULL for errors.
See also
ReleasePage()
WritePage()
DisposePage()
Implemented in stDiskPageManager, stPlainDiskPageManager, stMemoryPageManager, and stClientPageManager.
virtual stPage* stPageManager::GetPage (stPageID pageid) pure virtual
Returns the page with the given page ID. This method will return a valid page for reading/writing. Use WritePage() to write this page.
The returning instance of stPage will be locked to prevent its reuse by this page manager. Use ReleasePage() to unlock this instance.
Parameters
pageid The desired page id.
Returns
The page or NULL for an invalid page ID.
See also
WritePage()
ReleasePage()
Implemented in stDiskPageManager, stPlainDiskPageManager, stMemoryPageManager, and stClientPageManager.
long int stPageManager::GetReadCount () inline
Gets the number of reads performed since the last call of ResetStatistics().
See also
ResetStatistics()
GetWriteCount()
Definition at line 235 of file stPageManager.h.
long int stPageManager::GetWriteCount () inline
Gets the number of writes performed since the last call of ResetStatistics().
See also
ResetStatistics()
GetReadsCount()
Definition at line 247 of file stPageManager.h.
virtual bool stPageManager::IsEmpty () pure virtual
This method will checks if this page manager is empty. If this method returns true, the stSlimTree will create a new tree otherwise it will continue to use the existing tree.
Returns
True if the page manager is empty or false otherwise.
Implemented in stDiskPageManager, stPlainDiskPageManager, stMemoryPageManager, and stClientPageManager.
virtual void stPageManager::ReleasePage (stPage * page) pure virtual
Releases this instace for reuse by this page manager. Since some implementations of page manager will reuse instances of stPage to avoid unnecessary resource reallocations, each page instance must be locked until it becomes unecessary.
The stSlimTree will always call this method when a stPage instance will not be used in a near future.
Parameters
page The locked page.
See also
GetPage()
GetHeaderPage()
Implemented in stDiskPageManager, stPlainDiskPageManager, stMemoryPageManager, and stClientPageManager.
Referenced by stDummyTree< ObjectType, EvaluatorType >::~stDummyTree().
virtual void stPageManager::ResetStatistics () inline virtual
Restarts the statistics.
See also
GetReadCount()
GetWriteCount()
GetAccessCount()
Reimplemented in stDiskPageManager.
Definition at line 222 of file stPageManager.h.
void stPageManager::UpdateReadCounter (unsigned long count = 1) inline protected
This method updates the read counter.
Parameters
count The number o reads to add to the counter.
Definition at line 272 of file stPageManager.h.
Referenced by stClientPageManager::GetPage().
void stPageManager::UpdateWriteCounter (unsigned long count = 1) inline protected
This method updates the write counter.
Parameters
count The number o writes to add to the counter.
Definition at line 281 of file stPageManager.h.
virtual void stPageManager::WriteHeaderPage (stPage * headerpage) inline virtual
This method writes the header page back to the page manager.
The default implementation calls the WritePage() to header page. If a page manager needs a special way to write the header page, this method must be overwritten.
As WritePage() do, this method do not releases the header page. You must call ReleasePage() to release it.
Parameters
headerpage The header page.
Reimplemented in stDiskPageManager, and stPlainDiskPageManager.
Definition at line 123 of file stPageManager.h.
References WritePage().
virtual void stPageManager::WritePage (stPage * page) pure virtual
Writes the given page to the disk. This method will write the page but will not release it. Use ReleasePage() to do it.
Parameters
page The page to be written.
See also
ReleasePage()
WriteHeaderPage()
Implemented in stDiskPageManager, stPlainDiskPageManager, stMemoryPageManager, and stClientPageManager.
Referenced by WriteHeaderPage().
The documentation for this class was generated from the following file:
stPageManager.h
Copyright © 2002-2003 GBDI-ICMC-USP