stTreeInformation Class Reference
GBDI Arboretum
Version Release 1
stTreeInformation Class Reference
#include <stTreeInformation.h>
Classes
struct stLevelInfo
struct stOptimalLevelInfo
Public Member Functions
stTreeInformation (int height, int objectCount)
virtual ~stTreeInformation ()
virtual int GetHeight ()
virtual int GetMinHeight ()
virtual int GetOptimalHeight ()
virtual int GetObjectCount ()
virtual double GetLocalFatFactor (int level)
virtual double GetGlobalFatFactor ()
virtual double GetMeanObjectSize ()
virtual double GetAbsoluteFatFactor ()
virtual void Invalidate ()
void UpdateIntersections (int level, int n=1)
void UpdateNodeCount (int level, int n=1)
void UpdateObjectCount (int level, int n=1)
void UpdateMeanObjectSize (stSize size)
void UpdateMinHeight (int height)
virtual bool HasOptimalTree ()
void SetOptimalTreeInfo (int height, int *objectCount, int *nodeCount)
void CalculateOptimalTreeInfo (int occupation)
stTreeInformation * Clone ()
Public Member Functions inherited from stTreeInfoResult
virtual ~stTreeInfoResult ()
Protected Member Functions
void Validate ()
void ResetData ()
void Calculate ()
Protected Attributes
int height
int minHeight
double fatFactor
double bloatFactor
int objectCount
stSize objectSizeSum
stSize objectSizeCount
stLevelInfo * levelData
stOptimalLevelInfo * optimalLevelData
int optimalHeight
bool ready
Detailed Description
This class implements the class stTreeInfoResult. It works as a form that each tree must fill in order to provide its statistics to users.
Author
Fabio Jun Takada Chino (chino.nosp@m.@icm.nosp@m.c.usp.nosp@m..br)
Marcos Rodrigues Vieira (mrvie.nosp@m.ira@.nosp@m.icmc..nosp@m.usp..nosp@m.br)
Definition at line 172 of file stTreeInformation.h.
Constructor & Destructor Documentation
stTreeInformation::stTreeInformation (int height, int objectCount)
Creates a new FatFactor result for a tree with a given height.
Parameters
height The maximum height of the tree.
Warning
For tree use only.
virtual stTreeInformation::~stTreeInformation () virtual
Disposes this FatFactor result.
Member Function Documentation
void stTreeInformation::Calculate () protected
This method uses the information available to calculate the FatFactor.
Since this method is a quite expensive, the flag ready is used to avoid unnecessary calls to this method. To assure this, never call this method directly, call Validate() instead.
Referenced by Validate().
void stTreeInformation::CalculateOptimalTreeInfo (int occupation)
This method calculates the optimal tree info based on the same rules used to calculate the best M-Tree and Slim-Tree configuration. It assumes that all objects are stored in the last level of the tree and the number of links in an internal node is equal to occupation.
Since not all trees follow these rules, a method called SetOptimalTreeInfo() may be used to fill the information about the optimal tree.
Parameters
occupation The maximum occupation of a node.
See also
SetOptimalTreeInfo()
Warning
For tree use only.
stTreeInformation* stTreeInformation::Clone ()
Returns a clone of this instance.
Todo:
This method is not complete.
virtual double stTreeInformation::GetAbsoluteFatFactor () inline virtual
Returns the absolute FatFactor for this tree. The result of this method is meanless if HasOptimalTree() returned false.
Implements stTreeInfoResult.
Definition at line 246 of file stTreeInformation.h.
References bloatFactor, and Validate().
virtual double stTreeInformation::GetGlobalFatFactor () inline virtual
Returns the global FatFactor.
Implements stTreeInfoResult.
Definition at line 229 of file stTreeInformation.h.
References fatFactor, and Validate().
virtual int stTreeInformation::GetHeight () inline virtual
Returns the maximum height of the tree.
Implements stTreeInfoResult.
Definition at line 190 of file stTreeInformation.h.
References height.
virtual double stTreeInformation::GetLocalFatFactor (int level) inline virtual
Returns the FatFactor for a given level.
Parameters
level The level number.
Implements stTreeInfoResult.
Definition at line 221 of file stTreeInformation.h.
References stTreeInformation::stLevelInfo::FatFactor, levelData, and Validate().
virtual double stTreeInformation::GetMeanObjectSize () inline virtual
Returns the mean size of the objects stored in the tree. This value is useful to help tree developers to calculate the optimal tree.
Implements stTreeInfoResult.
Definition at line 238 of file stTreeInformation.h.
References objectSizeCount, and objectSizeSum.
virtual int stTreeInformation::GetMinHeight () inline virtual
Returns the minimum height of the tree.
Implements stTreeInfoResult.
Definition at line 197 of file stTreeInformation.h.
References minHeight.
virtual int stTreeInformation::GetObjectCount () inline virtual
Returns the number of objects indexed by the tree.
Implements stTreeInfoResult.
Definition at line 212 of file stTreeInformation.h.
References objectCount.
virtual int stTreeInformation::GetOptimalHeight () inline virtual
Returns the optimal height of the tree. The result of this method is meanless if HasOptimalTree() returned false.
Implements stTreeInfoResult.
Definition at line 205 of file stTreeInformation.h.
References optimalHeight.
virtual bool stTreeInformation::HasOptimalTree () inline virtual
Returns true if this information includes the optimal tree data.
Implements stTreeInfoResult.
Definition at line 324 of file stTreeInformation.h.
References optimalLevelData.
virtual void stTreeInformation::Invalidate () inline virtual
This method invalidates the current calculated FatFactor data. These data will be recalculated again when required.
Implements stTreeInfoResult.
Definition at line 255 of file stTreeInformation.h.
References ready.
Referenced by UpdateIntersections(), UpdateNodeCount(), and UpdateObjectCount().
void stTreeInformation::ResetData () protected
Resets all data acquired from the tree. All fields are set to 0.
void stTreeInformation::SetOptimalTreeInfo (int height, int * objectCount, int * nodeCount)
Sets the information obout the optimal tree. This information is used to calculate some of the tree's statistics.
Parameters
height The optimal height of the tree.
objectCount The number of objects per level in the optimal tree.
nodeCount The number of nodes per level of the optimal tree.
See also
CalculateOptimalTreeInfo()
Warning
For tree use only.
void stTreeInformation::UpdateIntersections (int level, int n = 1) inline
Updates the number of intersections of a given level.
Parameters
level The desired level.
n Number of intersections to add (default = 1).
Warning
For tree use only.
Definition at line 266 of file stTreeInformation.h.
References stTreeInformation::stLevelInfo::Intersections, Invalidate(), and levelData.
void stTreeInformation::UpdateMeanObjectSize (stSize size) inline
Updates the mean size of the object by adding a new object entry. To make this computation more accurate, avoid to add a given object more than once.
Parameters
size Size of the serialized object in bytes.
Warning
For tree use only.
Definition at line 303 of file stTreeInformation.h.
References objectSizeCount, and objectSizeSum.
void stTreeInformation::UpdateMinHeight (int height) inline
Updates the minimum height of the tree. If the minimum height is constant, this method may be avoided.
Parameters
height The height of a minimum
Warning
For tree use only.
Definition at line 315 of file stTreeInformation.h.
References height, and minHeight.
void stTreeInformation::UpdateNodeCount (int level, int n = 1) inline
Updates the number of nodes of a given level.
Parameters
level The desired level.
n Number of nodes to add (default = 1).
Warning
For tree use only.
Definition at line 278 of file stTreeInformation.h.
References Invalidate(), levelData, and stTreeInformation::stLevelInfo::NodeCount.
void stTreeInformation::UpdateObjectCount (int level, int n = 1) inline
Updates the number of objects of a given level.
Parameters
level The desired level.
n Number of objects to add (default = 1).
Warning
For tree use only.
Definition at line 290 of file stTreeInformation.h.
References Invalidate(), levelData, and stTreeInformation::stLevelInfo::ObjectCount.
void stTreeInformation::Validate () inline protected
Updates the FatFactor data when required. It must be called once before all FatFactor returning method to assure the consistency of data.
See also
Invalidate()
Definition at line 471 of file stTreeInformation.h.
References Calculate().
Referenced by GetAbsoluteFatFactor(), GetGlobalFatFactor(), and GetLocalFatFactor().
Member Data Documentation
double stTreeInformation::bloatFactor protected
Value of the BloatFactor (the absolute FatFactor ?).
Definition at line 423 of file stTreeInformation.h.
Referenced by GetAbsoluteFatFactor().
double stTreeInformation::fatFactor protected
Value of the global FatFactor.
Definition at line 418 of file stTreeInformation.h.
Referenced by GetGlobalFatFactor().
int stTreeInformation::height protected
Height of the tree.
Definition at line 408 of file stTreeInformation.h.
Referenced by GetHeight(), and UpdateMinHeight().
stLevelInfo* stTreeInformation::levelData protected
Information about each level.
Definition at line 443 of file stTreeInformation.h.
Referenced by GetLocalFatFactor(), UpdateIntersections(), UpdateNodeCount(), and UpdateObjectCount().
int stTreeInformation::minHeight protected
Minimum height.
Definition at line 413 of file stTreeInformation.h.
Referenced by GetMinHeight(), and UpdateMinHeight().
int stTreeInformation::objectCount protected
Number of objects indexed by the tree.
Definition at line 428 of file stTreeInformation.h.
Referenced by GetObjectCount().
stSize stTreeInformation::objectSizeCount protected
Number of objects used to compute the mean object size.
Definition at line 438 of file stTreeInformation.h.
Referenced by GetMeanObjectSize(), and UpdateMeanObjectSize().
stSize stTreeInformation::objectSizeSum protected
Total object size used to compute the mean object size.
Definition at line 433 of file stTreeInformation.h.
Referenced by GetMeanObjectSize(), and UpdateMeanObjectSize().
int stTreeInformation::optimalHeight protected
The height of the optmal tree.
Definition at line 453 of file stTreeInformation.h.
Referenced by GetOptimalHeight().
stOptimalLevelInfo* stTreeInformation::optimalLevelData protected
Information about each level of the optmal tree.
Definition at line 448 of file stTreeInformation.h.
Referenced by HasOptimalTree().
bool stTreeInformation::ready protected
This flag is used to determine the availability of the FatFactor information. If this flag is false, it is necessary to call Calculate() to make the information ready to use.
See also
Validate()
Invalidate()
Definition at line 463 of file stTreeInformation.h.
Referenced by Invalidate().
The documentation for this class was generated from the following file:
stTreeInformation.h
Copyright © 2002-2003 GBDI-ICMC-USP